### ISSUE TITLE
顶部与侧边菜单联动

### ISSUE THREAD

**Issue by jaytu** [iczer/vue-antd-admin#102]
作者你好
后续是否会扩展顶部菜单呢，项目内容比较多的时候，可能会在头部分出子系统，不同的子系统，加载不同的侧边栏

**Comment by iczer** [comment]
你是指一二级菜单分离，顶部导航显示一级菜单，侧边显示二级或更深层级菜单吗？

**Comment by jaytu** [comment]
> 你是指一二级菜单分离，顶部导航显示一级菜单，侧边显示二级或更深层级菜单吗？

是的

**Comment by iczer** [comment]
后面会加这个功能

**Comment by iczer** [comment]
已添加分离菜单功能
