### ISSUE TITLE
单页签模式报错

### ISSUE THREAD

**Issue by PY-Jax** [iczer/vue-antd-admin#103]
设置`multiPage: false`
控制台报错`'$vnode' of undefined`

**Comment by iczer** [comment]
已修复

**Comment by PY-Jax** [comment]
你好，多页签模式下，刷新页面，只会保留当前页签，其它的页签不能保留吗
还有底部栏不能控制显示隐藏吗

**Comment by iczer** [comment]
vue 刷新相当于应用重新加载，多页签页面缓存会丢失，所以只保留当前路由页签。
就算保留了其它页签，其它页签页面内容的缓存也不能保留，所以保留没太大意义。

底部栏如果不需要可以自行去除，目前没加设置项隐藏底部

**Comment by iczer** [comment]
如果不考虑多页签缓存问题，可以把改造下 TabsView 将 pageList 存在 localStorage, 这样页签头就不会丢失。但页面内容还是保留不了的
