### ISSUE TITLE
关于权限的问题

### ISSUE THREAD

**Issue by Arc-zlz** [iczer/vue-antd-admin#104]
![image](https://user-images.githubusercontent.com/26889461/90874129-d6d25500-e3d1-11ea-894f-1ebde288723e.png)
authority: {
      permission: 'form',
      role: 'form'
 }
虽然官网说一个是按角色权限来分,一个是按权限 permission 来分 ,但是感觉用起来都一样,比如有个需求,
permission_1 = {
  id: 'form',                                    //角色ID
  operation: ['add', 'delete', 'edit', 'close']  //权限下的操作权限
}
permission_2 = {
  id: 'form',                                    //角色ID
  operation: ['add', 'delete', 'edit']  //权限下的操作权限
}
form_2 不能进入页面  没办法去控制

**Comment by Arc-zlz** [comment]
哦哦  谢谢解答 想问一下如果通过权限id控制
permission_1 = {
id: 'id1', //权限ID
operation: ['add', 'delete', 'edit', 'close'] //权限下的操作权限
}
permission_2 = {
id: 'id2', //权限ID
operation: ['add'] //权限下的操作权限
}
permission_3 = {
id: 'id3', //权限ID
operation: ['add, 'edit', 'close'] //权限下的操作权限
}
permission_4 = {
id: 'id4', //权限ID
operation: ['add', 'delete', 'edit'] //权限下的操作权限
}
有四种不同方式的权限,按照文档也就是说需要四个不同的权限id
const route = {
  name: '验权页面',
  path: 'auth/demo',
  meta: {
    authority: ['id1','id2','id3','id4'],
  },
  component: () => import('@/pages/demo')
}
我就要放四个权限id到meta吗,这样操作不是很复杂?

**Comment by iczer** [comment]
vue-antd-admin 的权限控制设计理念是这样的：

我们把进入页面看做是开门，打开门有两种方式：

**一、用钥匙开门**
打开同一个门的钥匙只有一种，不存在多种钥匙开一个门的情况（这相当于系统的 permission 方式验权，所以不存在为同个页面配置多种权限的情况）
**二、人脸识别开门** 
可以设置多个人的面部识别（这相当于系统的 roles 方式验权，可以为同个页面配置多个准入角色）

**Comment by iczer** [comment]
如果感兴趣，可以入群交流下，谈谈你的想法，这里沟通效率太低了。QQ群：610090280

**Comment by iczer** [comment]
我仔细看了下你的四种权限，其实应该是同一种，只是每个权限下的操作权限不同。这样你可以把它们设置为同一种permission权限，再为不同的用户配置不同的子操作权限operation。这样你就只需要为一个路由配置一个权限就行了
比如：

```
user1.permissions = 
[
  {
    id: 'userManage',
    operation: ['add', 'edit', 'close', 'delete']
  }
]

user2.permissions = 
[
  {
    id: 'userManage',
    operation: ['add']
  }
]

user3.permissions = 
[
  {
    id: 'userManage',
    operation: ['add', 'edit', 'close']
  }
]

user4.permissions = 
[
  {
    id: 'userManage',
    operation: ['add', 'edit', 'delete']
  }
]

const route = {
name: '验权页面',
path: 'auth/demo',
meta: {
authority: 'userManage',
},
component: () => import('@/pages/demo')
}
```

**Comment by Arc-zlz** [comment]
我找到更好的方法  用权限生成路由 动态动态加载
 const route = {
    name: '验权页面',
    path: 'auth/demo',
   meta: {
      pressiones:"show"
   },
   component: () => import('@/pages/demo')
}
 通过pressiones for循环判断pressiones  生成新的的路由数组  不过感谢回答  感谢作者的开源
