### ISSUE TITLE
样式设置画面下拉框弹不出来

### ISSUE THREAD

**Issue by git-caocui** [iczer/vue-antd-admin#105]
描述错误有关错误
    样式设置画面，内容区域宽度，动画效果，动画方向  下拉框弹不出来，表单页下拉框正常

操作手顺：
  1.正常登陆
  2.点击设置按钮
  3.切换内容区域宽度

操作系统：Win10
浏览器：chrome 84.0.4147.135

![2020-08-25_084213](https://user-images.githubusercontent.com/59867413/91109902-f1951a00-e6ae-11ea-8aa8-c98cd7db7302.png)

**Comment by iczer** [comment]
已修复
