### ISSUE TITLE
关于Pagelayout中的PageHeader的title与面包屑

### ISSUE THREAD

**Issue by hiRainn** [iczer/vue-antd-admin#106]
现在标签、面包屑以及PageHeader中的title都有页面的名称，虽然title可以自定义，但是不能为空，感觉3个地方都显示这个会有点多余，个人开发在实际应用中，经常会只有标签页显示页面名称，或者加上面包屑足矣，建议在PageHeader中是直接取的title，建议在PageLayout中的pageTitle返回允许取空值

```computed(){
  ...
  pageTitle() {
      let pageTitle = this.page && this.page.title
      return this.title || this.$t(pageTitle) || this.routeName
  }
...
}
 
```

**Comment by iczer** [comment]
page title 设置为空不生效的问题已解决（目前设置为false 或空字符串，均可隐藏title）。 
另增加全局关闭 PageTiltle 显示的配置项 showPageTitle，见 [/config/default/setting.config.js](https://github.com/iczer/vue-antd-admin/blob/master/src/config/default/setting.config.js#L20)
