### ISSUE TITLE
请问是否有做路由懒加载?

### ISSUE THREAD

**Issue by stack-stark** [iczer/vue-antd-admin#109]
我看build之后部署是一次性把所有的js都加载了,页面多了会影响首次加载速度吧?
![image](https://user-images.githubusercontent.com/46991054/91380276-31970100-e857-11ea-93f7-eaa26a6d21b4.png)

**Comment by iczer** [comment]
有做懒加载的，可以去预览地址看看
![image](https://user-images.githubusercontent.com/13096697/91388022-1a610f00-e869-11ea-8a75-ba1332d44eb5.png)

**Comment by iczer** [comment]
检查下你自己的路由配置，是不是懒加载写法

**Comment by iczer** [comment]
这里面有部分资源是利用 HTML5 的 [prefetch](https://www.jianshu.com/p/7f58ddfc1392) 特性做的预加载。并不影响首屏性能。如不需要，可在 vue.config.js 中自行关闭

**Comment by stack-stark** [comment]
好的
