### ISSUE TITLE
建议把面包屑放到 AdminHeader.vue

### ISSUE THREAD

**Issue by vzhougm** [iczer/vue-antd-admin#110]
![图片](https://img-blog.csdnimg.cn/20200827190801771.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L0dNaW5nWmhvdQ==,size_16,color_FFFFFF,t_70#pic_center)

**Comment by iczer** [comment]
目前保持设计与 ant design pro 一致。自己的项目可以根据实际需求修改
