### ISSUE TITLE
动态路由i18n问题

### ISSUE THREAD

**Issue by vzhougm** [iczer/vue-antd-admin#111]
![在这里插入图片描述](https://img-blog.csdnimg.cn/20200827191307342.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L0dNaW5nWmhvdQ==,size_16,color_FFFFFF,t_70#pic_center)

**Comment by iczer** [comment]
原项目没这个问题哦，看看是不是代码版本问题或者配置问题

**Comment by iczer** [comment]
可以看看是否跟这个bug相关 https://github.com/iczer/vue-antd-admin/commit/4e29918bac68e92a367bd8f7f02a8a51ca99aeae
