### ISSUE TITLE
混合导航-导航抖动

### ISSUE THREAD

**Issue by guoranred** [iczer/vue-antd-admin#115]
混合导航时顶部菜单鼠标移入是抖动
![image](https://user-images.githubusercontent.com/1814053/92542990-d9132b00-f27c-11ea-89e8-8463087a96a5.png)

**Comment by iczer** [comment]
没发现你说的情况，可以看看演示地址是否存在你说的情况，https://iczer.gitee.io/vue-antd-admin/
能否提供下你的操作系统类型，浏览器类型及版本号

**Comment by guoranred** [comment]
> 没发现你说的情况，可以看看演示地址是否存在你说的情况，https://iczer.gitee.io/vue-antd-admin/
> 能否提供下你的操作系统类型，浏览器类型及版本号

家里的电脑 试了一下没有问题 公司的电脑周一去看看浏览器版本

混合导航-不固定Header时 在IE11下 切换顶部菜单时 顶部菜单会闪烁一下

**Comment by iczer** [comment]
找到原因了，切换主题色时，会出现这个问题

**Comment by iczer** [comment]
已修复
