### ISSUE TITLE
我觉得响应式要被玩坏掉了喵？

### ISSUE THREAD

**Issue by yihuishou** [iczer/vue-antd-admin#12]
![qq 20180815084613](https://user-images.githubusercontent.com/26241263/44125915-baeea546-a067-11e8-95f8-b0a2195c23f7.png)

**Comment by iczer** [comment]
已修复：[a0a031b](https://github.com/iczer/vue-antd-admin/commit/a0a031b6f11dc8fa8bbca04a6007c93fdcc4ed7d)
