### ISSUE TITLE
layout=mix混合模式下，异步加载路由会报错。

### ISSUE THREAD

**Issue by mrdznet** [iczer/vue-antd-admin#121]
**Describe the bug**
layout=mix混合模式下，异步加载路由会报错。
在登陆界面，不需要加载头部菜单，只有登陆成功后，才会获取路由，获取路由后，才应该加载头部菜单。

现在逻辑上稍微有点问题。

**Comment by mrdznet** [comment]
\src\store\modules\setting.js

`
firstMenu(state) {
      const {menuData} = state
//这里menuDAta还是空，直接选fullPath会报错。
      if (!menuData[0].fullPath) {
        formatFullPath(menuData)
      }
      return menuData.map(item => {
        const menuItem = {...item}
        delete menuItem.children
        return menuItem
      })
    },
`

**Comment by iczer** [comment]
已修复
