### ISSUE TITLE
切换使用 混合导航 => 收起左侧的菜单栏 => 左侧的菜单字体并未居中显示

### ISSUE THREAD

**Issue by shiyuq** [iczer/vue-antd-admin#125]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by guoranred** [comment]
收起菜单栏时，显示图标，混合导航模式下应该给左侧一级菜单加上图标

**Comment by iczer** [comment]
需要在路由中自己给二级菜单配置图标

**Comment by iczer** [comment]
已修复 https://github.com/iczer/vue-antd-admin/commit/556b5bf6fc23415669ce0b0e568037329419b8a7
