### ISSUE TITLE
多页签刷新签头不保存

### ISSUE THREAD

**Issue by liujinzhu333** [iczer/vue-antd-admin#127]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by iczer** [comment]
已修复：https://github.com/iczer/vue-antd-admin/commit/bad44562e72a0d597c8bc10fb106ec134287ccf4

**Comment by kecikeci** [comment]
> 已修复：[bad4456](https://github.com/iczer/vue-antd-admin/commit/bad44562e72a0d597c8bc10fb106ec134287ccf4)

刷新后标签页保留了，但是别的页面填的数据，在重新打开页面时，数据没有了

**Comment by iczer** [comment]
如果你想保留数据，就不要刷新。刷新本来就会重置网页内容。如果保留内容，刷新就没意义了。

**Comment by iczer** [comment]
如果是想要刷新单个页签内容的功能，另外提个issue

**Comment by kecikeci** [comment]
> 如果是想要刷新单个页签内容的功能，另外提个issue

好的  谢谢
