### ISSUE TITLE
能否增加刷新当前标签的功能

### ISSUE THREAD

**Issue by kecikeci** [iczer/vue-antd-admin#132]
![QQ截图20200930161215](https://user-images.githubusercontent.com/32811349/94661645-ea120200-0339-11eb-8609-897f79fa3cd5.png)

可以加在这个位置

**Comment by iczer** [comment]
刷新功能已添加

**Comment by kecikeci** [comment]
> 刷新功能已添加

感谢大佬  大佬NB
