### ISSUE TITLE
动态路由菜单点击报错

### ISSUE THREAD

**Issue by dpjs** [iczer/vue-antd-admin#137]
动态路由正常加载，菜单点击报错
vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in render: "TypeError: Cannot read property 'desc' of undefined"

found in

---> <PageView> at src/layouts/PageView.vue
       <PageToggleTransition> at src/components/transition/PageToggleTransition.vue
         <Anonymous>
           <ALayoutContent>
             <Anonymous>
               <ALayout>
                 <Anonymous>
                   <ALayout>
                     <AdminLayout> at src/layouts/AdminLayout.vue
                       <TabsView> at src/layouts/tabs/TabsView.vue
                         <ALocaleProvider>
                           <LocaleReceiver>
                             <AConfigProvider>
                               <App> at src/App.vue
                                 <Root>
warn @ vue.runtime.esm.js?2b0e:619
logError @ vue.runtime.esm.js?2b0e:1884
globalHandleError @ vue.runtime.esm.js?2b0e:1879
handleError @ vue.runtime.esm.js?2b0e:1839
Vue._render @ vue.runtime.esm.js?2b0e:3550
updateComponent @ vue.runtime.esm.js?2b0e:4066
get @ vue.runtime.esm.js?2b0e:4479
run @ vue.runtime.esm.js?2b0e:4554
flushSchedulerQueue @ vue.runtime.esm.js?2b0e:4310
eval @ vue.runtime.esm.js?2b0e:1980
flushCallbacks @ vue.runtime.esm.js?2b0e:1906
Promise.then (async)
timerFunc @ vue.runtime.esm.js?2b0e:1933
nextTick @ vue.runtime.esm.js?2b0e:1990
queueWatcher @ vue.runtime.esm.js?2b0e:4402
update @ vue.runtime.esm.js?2b0e:4544
notify @ vue.runtime.esm.js?2b0e:730
reactiveSetter @ vue.runtime.esm.js?2b0e:1055
eval @ vue-router.esm.js?8c4f:2922
eval @ vue-router.esm.js?8c4f:2921
updateRoute @ vue-router.esm.js?8c4f:2342
eval @ vue-router.esm.js?8c4f:2196
eval @ vue-router.esm.js?8c4f:2330
step @ vue-router.esm.js?8c4f:1934
step @ vue-router.esm.js?8c4f:1941
step @ vue-router.esm.js?8c4f:1941
step @ vue-router.esm.js?8c4f:1941
runQueue @ vue-router.esm.js?8c4f:1945
eval @ vue-router.esm.js?8c4f:2325
step @ vue-router.esm.js?8c4f:1934
eval @ vue-router.esm.js?8c4f:1938
eval @ vue-router.esm.js?8c4f:2312
eval @ vue-router.esm.js?8c4f:2060
eval @ vue-router.esm.js?8c4f:2136
Promise.then (async)
eval @ vue-router.esm.js?8c4f:2083
eval @ vue-router.esm.js?8c4f:2104
eval @ vue-router.esm.js?8c4f:2104
flatMapComponents @ vue-router.esm.js?8c4f:2103
eval @ vue-router.esm.js?8c4f:2039
iterator @ vue-router.esm.js?8c4f:2290
step @ vue-router.esm.js?8c4f:1937
step @ vue-router.esm.js?8c4f:1941
step @ vue-router.esm.js?8c4f:1941
step @ vue-router.esm.js?8c4f:1941
eval @ vue-router.esm.js?8c4f:1938
eval @ vue-router.esm.js?8c4f:2312
redirectGuard @ guards.js?e8f8:79
eval @ routerUtil.js?89a5:241
iterator @ vue-router.esm.js?8c4f:2290
step @ vue-router.esm.js?8c4f:1937
eval @ vue-router.esm.js?8c4f:1938
eval @ vue-router.esm.js?8c4f:2312
authorityGuard @ guards.js?e8f8:55
eval @ routerUtil.js?89a5:241
iterator @ vue-router.esm.js?8c4f:2290
step @ vue-router.esm.js?8c4f:1937
eval @ vue-router.esm.js?8c4f:1938
eval @ vue-router.esm.js?8c4f:2312
loginGuard @ guards.js?e8f8:35
eval @ routerUtil.js?89a5:241
iterator @ vue-router.esm.js?8c4f:2290
step @ vue-router.esm.js?8c4f:1937
eval @ vue-router.esm.js?8c4f:1938
eval @ vue-router.esm.js?8c4f:2312
progressStart @ guards.js?e8f8:19
eval @ routerUtil.js?89a5:241
iterator @ vue-router.esm.js?8c4f:2290
step @ vue-router.esm.js?8c4f:1937
runQueue @ vue-router.esm.js?8c4f:1945
confirmTransition @ vue-router.esm.js?8c4f:2320
transitionTo @ vue-router.esm.js?8c4f:2193
init @ vue-router.esm.js?8c4f:2913
beforeCreate @ vue-router.esm.js?8c4f:1271
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
callHook @ vue.runtime.esm.js?2b0e:4219
Vue._init @ vue.runtime.esm.js?2b0e:5004
Vue @ vue.runtime.esm.js?2b0e:5085
eval @ main.js?56d7:24
./src/main.js @ app.js:3127
__webpack_require__ @ app.js:854
fn @ app.js:151
1 @ app.js:3579
__webpack_require__ @ app.js:854
checkDeferredModules @ app.js:46
(anonymous) @ app.js:994
(anonymous) @ app.js:997
Show 52 more frames

vue.runtime.esm.js?2b0e:1888 TypeError: Cannot read property 'desc' of undefined
    at VueComponent.desc (PageView.vue?3897:28)
    at Watcher.get (vue.runtime.esm.js?2b0e:4479)
    at Watcher.evaluate (vue.runtime.esm.js?2b0e:4584)
    at VueComponent.computedGetter [as desc] (vue.runtime.esm.js?2b0e:4836)
    at Object.get (vue.runtime.esm.js?2b0e:2072)
    at Proxy.render (eval at ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/.cache/vue-loader","cacheIdentifier":"07031b5e-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js?!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/layouts/PageView.vue?vue&type=template&id=07175cda&scoped=true& (app.js:1415), <anonymous>:10:26)
    at VueComponent.Vue._render (vue.runtime.esm.js?2b0e:3548)
    at VueComponent.updateComponent (vue.runtime.esm.js?2b0e:4066)
    at Watcher.get (vue.runtime.esm.js?2b0e:4479)
    at Watcher.run (vue.runtime.esm.js?2b0e:4554)

**Comment by iczer** [comment]
可入群反馈问题
