### ISSUE TITLE
advance table动态展示与隐藏列不生效

### ISSUE THREAD

**Issue by yjqGitHub** [iczer/vue-antd-admin#139]
当我给column 设置align:'center' 时，勾选check box 动态移除和展示header 时正常的，但是body里面的就不会有变化，去掉align:'center'  就正常了
`{
          dataIndex: 'schedName',
          slots: { title: 'schedNameTitle' },
          // align: 'center',
        },
        {
          dataIndex: 'jobName',
          slots: { title: 'jobNameTitle' },
          align: 'center',
        },`

**Comment by Cainozoic** [comment]
我也遇到了同样的问题

**Comment by iczer** [comment]
已修复：https://github.com/iczer/vue-antd-admin/commit/97979c5059e2846a0180954060960c5e2216f35c
