### ISSUE TITLE
折叠侧栏菜单后页面联动问题

### ISSUE THREAD

**Issue by SilenceDN** [iczer/vue-antd-admin#14]
![debug](https://user-images.githubusercontent.com/16896067/44144786-73397ede-a0bb-11e8-8859-80d8a6e47de3.gif)

**Comment by iczer** [comment]
已修复：[3e9e485](https://github.com/iczer/vue-antd-admin/commit/3e9e48565c691c00ba1bf1219699543f5ab6bc5b)
