### ISSUE TITLE
多页签模式缓存 导致一级导航修改代码时页面会空，需要手动刷新

### ISSUE THREAD

**Issue by dengZhiNeng** [iczer/vue-antd-admin#141]
一级导航 修改代码时或删掉代码时会导致页面无法更新，需要手动刷新，页面会展示空，需要关掉多页签模式，就好了！

**Comment by iczer** [comment]
已修复：https://github.com/iczer/vue-antd-admin/commit/98f6a05ac9ada07ab0e0440c57c6854fd1ec7e1c
