### ISSUE TITLE
卡顿、甚至浏览器卡死

### ISSUE THREAD

**Issue by coderchs** [iczer/vue-antd-admin#148]
在开启多个tab后 会出现浏览器卡死的情况 请问有遇到过这种情况吗

**Comment by iczer** [comment]
提供下浏览器版本型号，另外可以看看预览网址是否也会卡死，如果预览地址也会卡死，那可能跟电脑配置和浏览器有关

**Comment by coderchs** [comment]
浏览器版本：chrome 86.0.4240.183（正式版本） （64 位）     预览网址不会卡死的 就这个会卡死

**Comment by coderchs** [comment]
查看cpu占用也非常的高 
![image](https://user-images.githubusercontent.com/32215076/98511047-215fc100-229f-11eb-8fd7-c764fcce57dc.png)
