### ISSUE TITLE
面板间隙过大喵？

### ISSUE THREAD

**Issue by yihuishou** [iczer/vue-antd-admin#15]
![qq 20180816093857](https://user-images.githubusercontent.com/26241263/44182163-486acf00-a138-11e8-8503-48c389c1e580.png)

**Comment by iczer** [comment]
应该是上下面年半间隙过小

**Comment by iczer** [comment]
应该是上下面板间隙过小汪

**Comment by iczer** [comment]
已修复：[cf1a4d2](https://github.com/iczer/vue-antd-admin/commit/cf1a4d2f7bc9a698f9f8012f2a9c2835c62e4da8)
