### ISSUE TITLE
希望增加需求：多标签模式下动态修改标签名字

### ISSUE THREAD

**Issue by kkjj-kj** [iczer/vue-antd-admin#150]
希望增加需求：多标签模式下动态修改标签名字

例如 查看详情时通常会跳转详情页 tab上的名字应为项目名称 现在page.title不可动态配置

**Comment by fendou** [comment]
同上

**Comment by iczer** [comment]
功能已增加：https://github.com/iczer/vue-antd-admin/commit/ae2b7a86ef8d83141a05b6972c9a03258381ba2f

**Comment by fendou** [comment]
厉害了
