### ISSUE TITLE
多页签模式下禁止缓存的功能

### ISSUE THREAD

**Issue by kkjj-kj** [iczer/vue-antd-admin#154]
管理后台需要处理数据都是比较新的用到的缓存场景较少
多页签模式下建议禁止缓存的功能

**Comment by fendou** [comment]
能自由选择哪个页面禁止缓存不?

**Comment by iczer** [comment]
功能已增加，setting.config.js 文件中设置 cachePage 可全局控制是否缓存页面数据。默认为 true
路由配置 meta.page.cacheAble 可控制指定页面是否缓存数据，默认为 true

**Comment by kkjj-kj** [comment]
终于等到你
