### ISSUE TITLE
高级表格静态数据能渲染，从后台读取的数据渲染不上

### ISSUE THREAD

**Issue by zhoushuai13** [iczer/vue-antd-admin#159]
如题，把静态数据放在axios请求的回调中也不能渲染，把静态数据直接放在created或mounted中能渲染

**Comment by iczer** [comment]
不会吧，演示代码就是axios 获取的数据，没有问题啊

**Comment by zhoushuai13** [comment]
修改组件后可以渲染了，修改方法：在src/components/table/AdvanceTable.vue中将...$options.propsData替换为...$options，另外这样修改是默认没有表头的，可将props中的showHeader赋予一个默认值true，即`showHeader: {type:Boolean,default:true}`

**Comment by zhoushuai13** [comment]
修改组件后可以渲染了，修改方法：在src/components/table/AdvanceTable.vue的computed中添加新的计算属性
tableProps() {
	let tableProps = {...this.$props}
	return tableProps
}
将...$options.propsData替换为...tableProps，另外这样修改是默认没有表头的，可将props中的showHeader赋予一个默认值true，即showHeader: {type:Boolean,default:true}

**Comment by iczer** [comment]
你是异步获取列配置吗？

**Comment by iczer** [comment]
已修复
