### ISSUE TITLE
小屏幕菜单的悬浮抽屉按钮消失了喵？

### ISSUE THREAD

**Issue by yihuishou** [iczer/vue-antd-admin#16]
![123](https://user-images.githubusercontent.com/26241263/44182646-69342400-a13a-11e8-8ae2-1d13022435a6.gif)

最新版的Pro 给改没了？？

**Comment by iczer** [comment]
小屏幕适配工作还在进行中，后面的开发工作会参考:[ pro beta版](https://beta.preview.pro.ant.design/)，取消了抽屉按钮

**Comment by iczer** [comment]
![image](https://user-images.githubusercontent.com/13096697/44189027-a953d080-a153-11e8-9cde-7f7016ebd7c5.png)
这个按钮也可以打开菜单，功能重叠了。
如果有需要，后面可以做成可配置抽屉按钮是否显示

**Comment by yihuishou** [comment]
没有重复吧。当下拉页面的时候，顶部的导航栏并没有固定喵。

**Comment by yihuishou** [comment]
知道为啥没了，Pro2 右边加了个抽屉。加个配置选项吧喵。

**Comment by iczer** [comment]
好主意

**Comment by yihuishou** [comment]
![223](https://user-images.githubusercontent.com/26241263/44243736-4e79b200-a203-11e8-8547-c20b71e7c47b.gif)
给你看个宝贝喵？（开发中的 Pro2）

**Comment by iczer** [comment]
在开发计划中哈

**Comment by nabaonan** [comment]
@yihuishou 这个不是beta版的antd pro吗？难道就是pro2？

**Comment by yihuishou** [comment]
@nabaonan 没错~就是Pro 2

**Comment by nabaonan** [comment]
@yihuishou 以为是1的改进版，感觉改动其实不算很大
