### ISSUE TITLE
高级表格 - 高级搜索 select 暂不支持异步问题

### ISSUE THREAD

**Issue by zouyinghao** [iczer/vue-antd-admin#160]
高级表格中，select 高级搜索暂不支持异步请求数据，我的想法是在dataType为“select”的columns中，添加一个dictionary字段，该字段是“string”类型，传递数据字典的code，在SearchArea.vue中，判断 search.dictionary是否存在，存在即请求接口，拿到数据字典。将 数据字典获取的数据放到 select 高级搜索下拉框中。

**Comment by iczer** [comment]
已修复
