### ISSUE TITLE
打开modal时，页面滚动条的部分会多出一部分白色区域，导致页面抖动

### ISSUE THREAD

**Issue by febelery** [iczer/vue-antd-admin#162]
打开modal时，页面滚动条的部分会多出一部分白色区域，导致页面抖动
![1](https://s3.ax1x.com/2020/11/26/D0Mi9g.png)

![2](https://s3.ax1x.com/2020/11/26/D0MjGF.png)

**Comment by Huitimkit** [comment]
+1

**Comment by iczer** [comment]
已修复
