### ISSUE TITLE
大神什么时候考虑支持vue3？

### ISSUE THREAD

**Issue by mashuangwei** [iczer/vue-antd-admin#164]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by iczer** [comment]
2021 年 1月 正式开始 vue-antd-admin 2.0 的开发工作 及 vue3 的支持工作

**Comment by febelery** [comment]
> 2021 年 1月 正式开始 vue-antd-admin 2.0 的开发工作 及 vue3 的支持工作

2.0 和 1.0 有啥区别呢？

**Comment by iczer** [comment]
* 代码重构，框架功能及插件支持插拔式扩展，更简洁，更易用
* 扩充页面模板库 及 内置组件库
* 提供框架开发脚手架，支持 yarn 及 node 方式安装
* 优化主题配置功能，提供更精细化、更易用的定制方案

**Comment by iczer** [comment]
以上为 2.0 的目标，先画个饼在这儿 🤣

**Comment by collinslin** [comment]
哈哈  明年就能用vue3.0版本   希望后续可以添加ts版本的支持

**Comment by ChenWeihua123** [comment]
膜拜，正好跟着大神一起学习vue3 哈哈哈

**Comment by jthinking** [comment]
非常期待，绝对能火起来，ant-design-vue-pro这个项目已经废了，开源版不再支持vue3了，搞起了收费模式

**Comment by 734839030** [comment]
坐等楼主的vue3 版本

**Comment by hanrea** [comment]
大神，预计几月发beta版本呀，支持TypeScript么？

**Comment by iczer** [comment]
beta 版本已发布，进群了解

**Comment by iczer** [comment]
vue3 版 demo地址：https://github.com/stepui/stepin-template

**Comment by huang-xiong** [comment]
请问能否支持TS呢?
