### ISSUE TITLE
弹性布局有问题

### ISSUE THREAD

**Issue by FirewoodKing** [iczer/vue-antd-admin#168]
在页面宽度缩小到1000px时，页面布局出现严重问题

![微信截图_20201208180727](https://user-images.githubusercontent.com/52149414/101469923-4cadfc80-3980-11eb-95a8-de624d9a4d9a.png)

**Comment by iczer** [comment]
这个问题很早之前解决了，你这个是什么版本的呢
![Uploading image.png…]()
