### ISSUE TITLE
登录样式边没了

### ISSUE THREAD

**Issue by nabaonan** [iczer/vue-antd-admin#17]
![image](https://user-images.githubusercontent.com/17247526/44223465-49444500-a1ba-11e8-8fcb-44b3be85c351.png)

**Comment by iczer** [comment]
可以提供下系统和浏览器版本吗

**Comment by iczer** [comment]
可以提供下系统和浏览器版本吗

**Comment by iczer** [comment]
可以提供下系统和浏览器版本吗

**Comment by nabaonan** [comment]
window10 chrome65.0.3325.181 @iczer  登录切换到手机号登录

**Comment by iczer** [comment]
已修复：[7f6f4a2](https://github.com/iczer/vue-antd-admin/commit/7f6f4a2b15308a9ee82c6d5d654b7d9be0148cea)
