### ISSUE TITLE
why is i18n so complicated

### ISSUE THREAD

**Issue by ziluohuanghun** [iczer/vue-antd-admin#173]
我发现在项目中，i18n 的实现有些复杂，每一个页面都有它的身影。可能我还理解额不够透彻，但我觉得应该有更好的办法来管理国际化数据

下面的内容基于我自己的理解。如果理解不对，请指出，多谢。

首先，i18n 的数据可以保存为一个 json，这样，所有的数据不会散落在每个地方，用户可以很方便的维护这个 json 数据。当然这个数据只包含用户的数据，不包括 ant 框架和其他 ui 框架中的数据

其次，在APP开始运行时，通过解析 json 数据，得到不同语言的集合并注入 i18n，这样，可以在任何页面访问

当切换语言的时候，只需要直接变更 i18n 的 locale， 而不再有其他任何逻辑

对于一些惰性的数据，如 echarts 图中渲染的数据，可以使用 computed 计算属性来得到

我大概写了一下思路， 

这是 language.json  数据
```
{
  "version": "1.0.0",
  "langOrder": ["option_key", "zh", "en", "ru"],
  "desc": "",
  "dict": {
    "login": [
      ["", "登录", "Login", "вход"],
      ["", "退出", "Logout", "выход"],
      ["", "用户名", "Username", "Имя пользователя"],
      ["", "登录密码", "Password", "пароль входа"],
      [
        "welcome",
        "欢迎 <span class=username>{username}</span> 登录",
        "Welcome <span class=username>{username}</span>",
       "Добро пожаловать <span class=username>{username}</span>"
      ]
    ]
   ]
  }
}
```
解析 json 数据形成 i18n 需要的格式
```
import dictionary from './language.json'

const { dict, langOrder } = dictionary

interface DictObj {
  zh?: object;
  en?: object;
}
const language: DictObj = {}

langOrder.forEach((_item, index) => {
  const _lang = {}
  if (index) { 
    for (const key in dict) {
      const data = {}
      dict[key].forEach((item: string[]) => {
        const _ = item[0] ? item[0] : item[1]
        data[_] = item[index]
      })
      _lang[key] = data
    }
  }
  language[langOrder[index]] = _lang
})

export default {
  zh: {
    ...language.zh
  },
  en: {
    ...language.en
  }
}
```
注入到 i18n 中
```
import Vue from 'vue'
import VueI18n from 'vue-i18n'
import language from './lang'
Vue.use(VueI18n)
const i18n = new VueI18n({
  locale: 'zh',
  messages: language
})
new Vue({
 i18n
})
```
使用
```
// in js
this.$t('login.登录')
// in template
$t('login.登录')
```

希望能探讨出 i18n 更优雅的使用方式

**Comment by iczer** [comment]
首先，感谢建议。
根据你所描述，我总结一下几点
* i18n的全局配置
Admin 的整个应用中，使用的是同一个 i18n 实例，所以是支持全局统一配置 i18n 语言数据的。
你可以在应用始化时加载所有的语言数据，这些数据在所有页面都是可以直接使用的。
如果页面想单独配置国际化数据，页面可以添加自己专属的国际化配置，两种配置方式并不冲突。
* i18n的 语言切换
目前项目的语言切换就是通过 i18n 的 locale 改变切换的。
另外，因为组件库 antd vue 的国际化用的不是 i18n，所以Admin的语言切换还关联了antd vue 组件库的语言切换逻辑。
不知道你说的切换复杂是不是指这个。
* i18n json 数据解析
你这种 json 解析的方式确实不错，简化了语言配置代码。
之前也考虑过类似你这种格式的，但为了避免增加用户学习成本（用户只需学习 i18n.js 即可），还是采用了 i18n 原生的格式。
如果是个人的开发项目，用你这种格式，然后解析成i18n配置的方式还是很不错的。
