### ISSUE TITLE
V0.7.2   更改角色权限控制后台菜单不能正确显示菜单项（Changing role permission control background menu can't display menu items correctly）

### ISSUE THREAD

**Issue by collinslin** [iczer/vue-antd-admin#179]
- Version [0.7.2]

**Describe the bug**
If the roles with different permissions are changed, the menu items cannot be displayed correctly in the background menu.

**Steps to reproduce the behavior**
1, Set role permissions on the router config list
2. Log in to the account without permission, and the menu item will be displayed normally (no list item will be displayed)
3. Exit account without permission
4. After logging in the account with permission, the menu item is not displayed correctly (no list item)

**Expected behavior**
After logging in the authorized account, the menu items will be displayed correctly (with list items)

版本号：0.7.2
bug：如果更改了具有不同权限的角色，则无法在后台菜单中正确显示菜单项。

重现行为的步骤：
1.在路由配置里面对列表进行设置角色权限。
2.登录没有权限的账号，菜单项正常显示（不显示列表项）。
3.退出没有权限的帐户。
4登录有权限的帐户后，菜单项显示不正确（无列表项）。

预期行为：
登录有权限的账户后，菜单项将正确显示（带列表项）

**Comment by iczer** [comment]
已修复
