### ISSUE TITLE
幻觉喵？

### ISSUE THREAD

**Issue by yihuishou** [iczer/vue-antd-admin#18]
![qq 20180817102042](https://user-images.githubusercontent.com/26241263/44244608-54719200-a207-11e8-8514-3fe28a60988d.png)
总感觉左侧好像窄了一点？是我的错觉喵？

**Comment by iczer** [comment]
确实是错觉，里面卡片border颜色和页面背景色比较接近，导致看起来好像看起来窄一些。去掉border后就没这个错觉了。
