### ISSUE TITLE
深色模式下 box-shadow 颜色不正常

### ISSUE THREAD

**Issue by XuedongZhou** [iczer/vue-antd-admin#182]
**Describe the bug**
深色模式下 box-shadow 颜色不正常，主题切换后 box-shadow 颜色未改变

**Expected behavior**
 box-shadow 的颜色应该随主题切换一起改变

**Comment by iczer** [comment]
有改变哦，默认，浅色模式下 box-shadow 底色为黑色。深色模式下 box-shadow 底色为白色。
不知道你说的 box-shadow 颜色没改变是哪个页面或者组件呢？

**Comment by XuedongZhou** [comment]
我的意思是深色模式下 box-shadow 应该为深色更加合适，为浅色不太搭

**Comment by Leeiio** [comment]
认同深色模式也就是night模式下的box-shadow应该为深色
