### ISSUE TITLE
卡片列表无法显示header内容

### ISSUE THREAD

**Issue by nabaonan** [iczer/vue-antd-admin#19]
操作步骤，
1在登录页点击注册用户，进入到主界面
2点击列表-》卡片列表
3你会发现header中那些文档连接没有了
但是你刷新页面就会出来了
前后做个对比
![image](https://user-images.githubusercontent.com/17247526/44247744-2e54ed80-a219-11e8-8eb1-2dab52d5e72a.png)

![image](https://user-images.githubusercontent.com/17247526/44247759-3f056380-a219-11e8-9a1c-fd6bb170d3c0.png)

**Comment by iczer** [comment]
已修复：[f4601a4](https://github.com/iczer/vue-antd-admin/commit/f4601a4b5d8b66de8def16cc4e4a2168656209d7)
