### ISSUE TITLE
我在config文件中配置了mode: 'light'，页面显示跟预览的不一致

### ISSUE THREAD

**Issue by pjr109** [iczer/vue-antd-admin#192]
**Describe the bug**
![image](https://user-images.githubusercontent.com/28778560/108817594-15500300-75f3-11eb-9583-0acc3ad52e81.png)

配置了config文件中的mode为‘light’，但是在界面预览的时候只有左边菜单的logo以及空白处为白色，页面其它部分还全是暗色的

**Comment by iczer** [comment]
修改配置文件需要重新启动
