### ISSUE TITLE
感觉这个的加载性能并不是很好。

### ISSUE THREAD

**Issue by gesions** [iczer/vue-antd-admin#194]
感觉性能好像不是很好呀，希望能好好考虑下性能这块。

**Comment by jackzoom** [comment]
貌似是layouts 中`PageLayout.vue`引起的，修改下就好了

**Comment by i-CNNN** [comment]
@jackzoom 怎么改呢?

**Comment by jackzoom** [comment]
@i-CNNN 没深读代码，我自己重新建了个`component`。它里面的扩展参数在我自己项目上应用不到

**Comment by xiaofuliang** [comment]
请问如何解决

**Comment by LiYuzZ** [comment]
希望能默认加上gizp压缩，不然初次打开时间确实有些慢
