### ISSUE TITLE
动态加载路由、菜单

### ISSUE THREAD

**Issue by awun0340** [iczer/vue-antd-admin#197]
动态加载路由
![image](https://user-images.githubusercontent.com/56752836/110207466-9e521e80-7ebe-11eb-8658-07c077b737c7.png)
这个component是写死的，怎么不遵循一定的规则让他自己去找
![image](https://user-images.githubusercontent.com/56752836/110207494-cb063600-7ebe-11eb-9de2-1b76e2da2566.png)
我加了几个页面，都显示不出来，只有demo可以显示，因为它注册了的。这个是需要自己去写component的路径的。希望加页面时它会自动找到该页面并注册路由

**Comment by iczer** [comment]
进群交流哈，这里用于 bug 报告 和 需求提交。
