### ISSUE TITLE
登录成功后，权限控制使高权限登录后侧边栏菜单显示不全

### ISSUE THREAD

**Issue by Tsick** [iczer/vue-antd-admin#199]
**Describe the bug**
切换身份登录，如果第二次登录的权限比第一次高，第二次进系统后左侧导航栏显示的是上一个用户所看到的。
**To Reproduce**
1、在mock里面login.js，将test用户的permissions的id设置为“1”。
2、第一次登录使用test身份登录。“查询表格”页面看不见。
3、退出登录，使用admin身份登录。“查询表格”依然看不见。
**Expected behavior**
切换身份登录后，侧边菜单能显示正确

**Comment by iczer** [comment]
已修复：[92a27fe](https://github.com/iczer/vue-antd-admin/commit/8ddc7c167c68b1eb9e1f216261cab3f1492a27fe)
