### ISSUE TITLE
安装包的时候无法下载chromedriver

### ISSUE THREAD

**Issue by myronlau** [iczer/vue-antd-admin#2]
Downloading https://chromedriver.storage.googleapis.com/2.40/chromedriver_win32.zip
Saving to C:\Users\Mxxxx\AppData\Local\Temp\chromedriver\chromedriver_win32.zip
ChromeDriver installation failed Error with http(s) request: Error: read ECONNRESET

请问chromedriver是必须的吗？因为没法科学上网下载不了，这影响使用呐

**Comment by iczer** [comment]
部分依赖包下载失败可以考虑切换国内镜像
npm:
```
npm config set registry https://registry.npm.taobao.org
```
yarn:
```
yarn config set registry https://registry.npm.taobao.org
```
