### ISSUE TITLE
主页右侧头像没有了

### ISSUE THREAD

**Issue by nabaonan** [iczer/vue-antd-admin#20]
如图所示：
![image](https://user-images.githubusercontent.com/17247526/44247790-6eb46b80-a219-11e8-972b-d249cb14516e.png)

 右侧头像缺失，不知是样式导致的吗？

**Comment by iczer** [comment]
页面刷新时state数据丢失导致，近期会增加js数据库存储state解决

**Comment by iczer** [comment]
已修复：[3053544](https://github.com/iczer/vue-antd-admin/commit/3053544b598747ba421c0992f8149f32ab617c77) & [e3c5f57](https://github.com/iczer/vue-antd-admin/commit/e3c5f57366aa2a1d6e926b2897b34289dea116fc)
