### ISSUE TITLE
table控件中，我希望固定列位置与设定列宽度同时使用报错

### ISSUE THREAD

**Issue by hardyfan** [iczer/vue-antd-admin#200]
我希望将一列固定在左侧，同时设置它的宽度，然后设置超出宽度后出现“...”。但是设置后不起作用。
好像时固定列与设置列宽度不能同时起作用。

请审核该问题，谢谢！

**Comment by iczer** [comment]
具体是哪个 table 组件呢。如果是 ant-designv-vue 的table 组件，需要到官方 仓库去提交bug。如果是项目内置的table 组件，还需更详细的复现步骤提供，也可入群交流哈。
