### ISSUE TITLE
重新登陆菜单会保持上一次的纪录

### ISSUE THREAD

**Issue by huixu123** [iczer/vue-antd-admin#201]
**Describe the bug**
重新登陆菜单会保持上一次的结果

查看代码有一个filterMenu()函数
`    if (menu.meta && menu.meta.invisible === undefined) {
      menu.meta.invisible = !hasAuthority(menu, permissions, roles)
      if (menu.children && menu.children.length > 0) {
        filterMenu(menu.children, permissions, roles)
      }
    }`
这段逻辑是不是有点问题，判端menu.meta.inisible是否等于undefined ，第一次登陆后会给invisible赋值。那不刷新重新登陆后是不是就不会重新赋值了

**Comment by iczer** [comment]
已修复：[92a27fe](https://github.com/iczer/vue-antd-admin/commit/8ddc7c167c68b1eb9e1f216261cab3f1492a27fe)
