### ISSUE TITLE
登录页面输入框边框缺失

### ISSUE THREAD

**Issue by nabaonan** [iczer/vue-antd-admin#21]
这个是登录![image](https://user-images.githubusercontent.com/17247526/44348284-91ba7600-a4cc-11e8-8fba-3c49fe10f5c3.png)
对比react版的pro
![image](https://user-images.githubusercontent.com/17247526/44348341-b57dbc00-a4cc-11e8-9ce7-d3f33ae34ac0.png)
缺少输入框左边的光圈

**Comment by iczer** [comment]
已修复：[6aa12b1](https://github.com/iczer/vue-antd-admin/commit/6aa12b13f5b0b64bef25d7df2eff17e2f3514ab4)，羡慕你们的像素眼，罒ω罒
