### ISSUE TITLE
请问如何在二级页面下新建一个编辑页面，并且保证菜单还是高亮的

### ISSUE THREAD

**Issue by 18714984191** [iczer/vue-antd-admin#211]

**Comment by Windancer** [comment]
如何理解菜单是高亮的？可否参考一下体验版的router尝试解决。

**Comment by 18714984191** [comment]
> 如何理解菜单是高亮的？可否参考一下体验版的router尝试解决。

![image](https://user-images.githubusercontent.com/54229220/115325572-6e38b380-a1be-11eb-894f-0d5072e8b80c.png)
情况再截图中已说明，想请教一下

**Comment by iczer** [comment]
入群沟通

**Comment by 2711687979** [comment]
请问这个问题解决了吗？遇到一样的问题，进群都没人讲话，哈哈哈

**Comment by iczer** [comment]
子级路由激活时，父级路由菜单会自动高亮；
如果内页路由不是外页路由的子路由， 在内页路由配置 meta.highlight 属性指定要高亮的菜单路由，属性值为需要高亮的菜单路由 fullPath 值 
<img width="572" alt="image" src="https://user-images.githubusercontent.com/13096697/187586997-6685124c-a206-431e-b6ab-4f34f6f46d8f.png">

**Comment by YourException** [comment]
![image](https://user-images.githubusercontent.com/37800407/187860915-0169f524-3c5b-4d97-ac75-61a430c18cbf.png)
并非如此。
如上图，1和2是属于父子关系，点击2进入“详情”，但需要保持其父级路由菜单高亮。
文档：页面/路由配置有这样一段描述：
![image](https://user-images.githubusercontent.com/37800407/187862022-44fe8c06-092b-45f7-b1e9-d85404787be5.png)
父级路由的组件必须配置为-视图组件：[PageView]、[TabsView]、[BlankView]。
此处的情况是：父级路由组件并非视图组件。

**Comment by YourException** [comment]
如果"查询表单"组件与"详情"组件是平级关系，反复切换"查询表单"和"详情"两个路由，然后返回，就会一直在两个路由间反复切换，但"查询表单"应该是父级路由(高亮)，如此就很奇怪。

**Comment by iczer** [comment]
highlight 属性就是为解决非父子路由高亮问题的。如果还是不能解决你的问题，在 qq 群 610090280 @我 详细沟通，入群答案: iczer
