### ISSUE TITLE
异步路由，在router.map.js里配置了meta不生效

### ISSUE THREAD

**Issue by mrt8544** [iczer/vue-antd-admin#219]
异步路由情况下，在router.map.js配置了meta。在异步路由加载完成后。meta不生效
router.map.js配置如下：
`Workplace: {
    name: '工作台',
    meta:{
      page:{
        closable: false
      }
    },
    component: () => import('@/pages/Workplace/Workplace')
  },`
异步路由加载完成后。
closable: false 没有生效。跟踪代码发现，异步路由加载完成后，meta为undefined

**Comment by iczer** [comment]
升级到最新版本
