### ISSUE TITLE
 请问大大是否基于Ant Design of Vue实现的？

### ISSUE THREAD

**Issue by lxkbest** [iczer/vue-antd-admin#22]
就是想问一下大大是自己实现的，还是基于 https://github.com/vueComponent/ant-design-vue 这个仓库实现的~

**Comment by seekwe** [comment]
是。话说看下代码几秒钟的事还要专门提交isset？

**Comment by lxkbest** [comment]
@seekwe 抱歉抱歉，我并非专业的前端，所以看代码去分析，对我来说可能花的时间比较长。所以就想确认下提个问题。

**Comment by lxkbest** [comment]
@seekwe 当然我也觉得大大应该在 README 说明。这样会有更多人关注你的项目

**Comment by iczer** [comment]
README 中有依赖说明哦，可能不是很显眼。

后面会把主要依赖放在更显眼的位置，感谢建议。

![image](https://user-images.githubusercontent.com/13096697/44500777-e3c1ee00-a6bc-11e8-9a5b-7516e52e4e8d.png)

**Comment by seekwe** [comment]
@lxkbest 我的错,我可能说的不清楚,看代码不是说看源代码,是代码文件 README.md或package.json 里面都有
