### ISSUE TITLE
可以提供一种统一的命名规范吗？

### ISSUE THREAD

**Issue by 332lfgb6** [iczer/vue-antd-admin#222]
![image](https://user-images.githubusercontent.com/51245335/118227104-92846900-b4ba-11eb-9002-51c155cfdcbe.png)
![image](https://user-images.githubusercontent.com/51245335/118227135-9fa15800-b4ba-11eb-9093-0a4fd6addfb9.png)
![image](https://user-images.githubusercontent.com/51245335/118227163-aa5bed00-b4ba-11eb-84f5-50a05bb27a53.png)
> 有些地方是驼峰命名法，有些地方是短线，有的地方是点，有的地方是大写字母开始。

**Comment by iczer** [comment]
感谢建议，正待改进改
