### ISSUE TITLE
路由mate配置了invisible: false,会导致权限控制失效

### ISSUE THREAD

**Issue by LiYuzZ** [iczer/vue-antd-admin#223]
1、根据文档，可通过invisible控制导航的显示和隐藏
![image](https://user-images.githubusercontent.com/29536326/118585227-0aa8a280-b7cb-11eb-8b3b-530cd999e3b9.png)

如果我在路由中配置了，invisible:true可以正常隐藏导航，
但是我想要显示的导航的时候会默认改回 invisible:false，(这个地方能改为false吗？还是设计的就是不显示导航就要删除invisible字段？)
改回false后权限控制就会失效
![image](https://user-images.githubusercontent.com/29536326/118647542-081e6b00-b814-11eb-83c6-1eff88784915.png)

因为filterMenu方法中
![image](https://user-images.githubusercontent.com/29536326/118584907-78a09a00-b7ca-11eb-8e21-6f63949b049b.png)

进入路由权限校验方法的条件是，if (menu.meta && menu.meta.invisible === undefined)，此时 menu.meta.invisible已经改为false。并不会进入权限校验的方法，判断改为 (menu.meta && !menu.meta.invisible)就会正常

此处是故意这么设置的吗，还是我使用的方式错了

**Comment by iczer** [comment]
当路由配置了 invisible 时，则菜单的显示与否已路由配置为准。
当路由未配置时，则根据用户权限配置来决定是否要显示菜单。
即路由 invisible 配置优先级 大于 权限配置。
用于要控制页面权限，但又想单独控制菜单是否显示的场景。
