### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by zhanghq** [iczer/vue-antd-admin#23]
![image](https://user-images.githubusercontent.com/745117/44503227-d9592180-a6c7-11e8-8b98-460bf867b65d.png)

**Comment by iczer** [comment]
应该是文件夹大小写问题导致，后面会修复这个问题，临时解决办法：
把 src\components\list\Search 文件夹名改为小写 src\components\list\search

**Comment by iczer** [comment]
已修复：[de8cd45](https://github.com/iczer/vue-antd-admin/commit/de8cd459eaf3a6713501bd0c3563417f94506285)
拉取最新代码即可解决

**Comment by zhanghq** [comment]
great
