### ISSUE TITLE
要大更新了喵？

### ISSUE THREAD

**Issue by yihuishou** [iczer/vue-antd-admin#25]
![00001](https://user-images.githubusercontent.com/26241263/45130866-1db2ea00-b1bd-11e8-9343-9e67072eb449.png)

**Comment by iczer** [comment]
是的，在更新中

**Comment by yihuishou** [comment]
加油~~

**Comment by zhangfugui727** [comment]
666

**Comment by sunweizhe** [comment]
能增加多标签页的功能吗

**Comment by iczer** [comment]
可以的，之前也有这个计划

**Comment by iczer** [comment]
@sunweizhe 多标签页功能已增加：[b818fd8](https://github.com/iczer/vue-antd-admin/commit/b818fd8a29fb27d9efb2165c1bf2f1145ff2348b)
目前还没有页签右键菜单功能，后续会加上

**Comment by sunweizhe** [comment]
GREAT  ，太效率了
