### ISSUE TITLE
yarn install 安装出错

### ISSUE THREAD

**Issue by sunweizhe** [iczer/vue-antd-admin#26]
win10 x64  node 8.11.3  yarn 1.94
虽然安装组件报错,但是可以运行,目前没发现别的问题
error D:\web\git\antd\node_modules\level\node_modules\leveldown: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments:
Directory: D:\web\git\antd\node_modules\level\node_modules\leveldown
Output:
prebuild-install WARN install connect ETIMEDOUT 52.216.80.8:443

D:\web\git\antd\node_modules\level\node_modules\leveldown>if not defined npm_config_node_gyp (node "D:\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.11.3 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "D:\Program Files\Python\python.exe", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (D:\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (D:\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at D:\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\web\git\antd\node_modules\level\node_modules\leveldown

**Comment by iczer** [comment]
这个是npm环境问题，在安装[pouchdb](https://github.com/pouchdb/pouchdb)依赖时会报错，一般有如下两个原因：
* **1.python版本不支持**  
解决办法：安装python 2.7 或其他支持的版本
* **2.缺少windows build tool 环境**
解决办法：参考https://github.com/nodejs/node-gyp#installation
