### ISSUE TITLE
引入的 cdn 资源访问不了，导致页面也访问不了

### ISSUE THREAD

**Issue by Erindcl** [iczer/vue-antd-admin#284]
引入的 cdn 资源访问不了，导致页面也访问不了，并且cdn 资源访问不了是偶发性问题

![image](https://user-images.githubusercontent.com/26838689/146746921-112a974f-b6ed-4658-a2f6-f3f6791e4d41.png)

**Comment by CracKerMe** [comment]
JSdelivr 前段时间确实出问题了，比如有必要还是把 对应的文件上传到公司的CDN 去，确保使用安全

**Comment by CracKerMe** [comment]
（注：不建议将公共的CDN地址用于生产，因为该连接随时都可能会失效，导致项目挂掉，使用CDN方式记得锁定版本号）

**Comment by icoco** [comment]
能否去掉

**Comment by CracKerMe** [comment]
> 能否去掉

项目当前属于非维护状态，建议自己去处理，或者 你觉得去除CDN外链很重要， 可以自己去除后 ，发个PR

**Comment by icoco** [comment]
> 能否去掉

去掉就挂？ 能否简单打包方式？

**Comment by icoco** [comment]
了解，不过好奇，好像其他工程，没看到过手动挂vue运行环境， 也许问的问题比较初级^_^

**Comment by CracKerMe** [comment]
> 了解，不过好奇，好像其他工程，没看到过手动挂vue运行环境， 也许问的问题比较初级^_^

https://github.com/iczer/vue-antd-admin/blob/master/vue.config.js#L94
实际是生产环境采用了 指定CDN的方式将项目中用到的不会修改的库移出来。一般用于公司使用的CDN 或者 多个项目共用库的一种优化策略，如果不符合你们的业务需求 81-83 都可以移除。
