### ISSUE TITLE
v-auth 指令进行权限判断不正确

### ISSUE THREAD

**Issue by ThorSmallice** [iczer/vue-antd-admin#285]
用v-auth 对按钮进行权限判断不正确，使用master分支下 ，我在首页设置了一个测试按钮 使用v-auth="`add`" 是禁用状态的，vuex里面是可以看到permission 权限组中是有add这个权限的，v-auth不管如何设置按钮都是禁用状态

**Comment by coderjiang** [comment]
v-auth="`add`"

**Comment by ThorSmallice** [comment]
这三种方式 都不行




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "iczer/vue-antd-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月3日(星期一) 晚上9:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [iczer/vue-antd-admin] v-auth 指令进行权限判断不正确 (Issue #285)





 
v-auth="add"
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ThorSmallice** [comment]
我发了邮件截图给你了，你看看喔
