### ISSUE TITLE
【BUG】HeaderNotice 样式问题

### ISSUE THREAD

**Issue by iczer** [iczer/vue-antd-admin#29]
HeaderNotice 气泡浮层位置偏下，与ant design pro不一致；
切换tab时会导致位置偏移和宽度改变。
![image](https://user-images.githubusercontent.com/13096697/45858534-7d4def80-bd90-11e8-96a6-b202d5a499ed.png)
![image](https://user-images.githubusercontent.com/13096697/45858558-8fc82900-bd90-11e8-9c08-73341762cf70.png)

**Comment by nabaonan** [comment]
![image](https://user-images.githubusercontent.com/17247526/46908288-7a8b8800-cf53-11e8-96e6-3c4e9aa53ac0.png)
加一个样式

**Comment by sendya** [comment]
https://github.com/iczer/vue-antd-admin/blob/master/src/layouts/HeaderNotice.vue#L2

old:
```vue
<a-popover trigger="click" placement="bottomRight">
```
new:
```vue
<a-popover trigger="click" placement="bottomRight" :overlayStyle="{ width: '300px' }">
```

source: [文字提示 Tooltip](https://vuecomponent.github.io/ant-design-vue/components/tooltip-cn/#%E5%85%B1%E5%90%8C%E7%9A%84-API)

`overlayClassName` 或 `overlayStyle`  控制弹层宽度即可防止溢出

**Comment by iczer** [comment]
@nabaonan @sendya 感谢建议，最近忙别的事，所以这个项目有些耽搁了 :joy:
