### ISSUE TITLE
登录后再次访问localhost:8080还是跳转登录页面

### ISSUE THREAD

**Issue by GeminiSGX** [iczer/vue-antd-admin#295]
请问下这个问题怎么解决呀，浏览器中cookie信息是有的，正常情况登录之后再次访问localhost:8080应该直接跳转到首页呀

**Comment by qiangvei** [comment]
就让我这小白来回答你的问题吧

修改两个地方：路由映射文件 、 路由配置文件
`
......
{
      path: '/',
      name: '首页',
      component: TabsView,
      redirect: '/dashboard/workplace', // '/login',  **修改的地方**
      children: [
......
`
你可以看到，默认跳转到登陆页的，你把它改成你想要跳转的页面即可，我这里改成：/dashboard/workplace ，如果没登陆，进到这个页它会自动跳转去登陆页。
