### ISSUE TITLE
Ant Design Pro bate版本

### ISSUE THREAD

**Issue by qutz** [iczer/vue-antd-admin#3]
这个项目非常好，可以参考bate版本功能来完善
https://beta.preview.pro.ant.design/

**Comment by barrycom** [comment]
https://beta.preview.pro.ant.design/ 这个项目有交互了。哪里下载啊

**Comment by iczer** [comment]
还是原地址：https://github.com/ant-design/ant-design-pro/

**Comment by barrycom** [comment]
有相应的功能完善了吗？

**Comment by iczer** [comment]
ant design pro 官网已经更新到2.0版
更新细节，可查看 [ant-design-pro release 2.0.0](https://github.com/ant-design/ant-design-pro/releases/tag/2.0.0)

**Comment by barrycom** [comment]
请问有表单提交后如何数据到后台的操作吗？我新手不懂 所以问问 想学习下

**Comment by iczer** [comment]
可以先看下基础的：[AJAX](http://www.w3school.com.cn/ajax/index.asp)、[HTML<form>](http://www.w3school.com.cn/tags/tag_form.asp)
比较流行的异步请求js库：[axios](https://github.com/axios/axios)

**Comment by barrycom** [comment]
axios这个项目中集成了吗 ajax我知道 我是想看看提交表单是时后续的写法是咋样的 怎么样去获取表单值和传递的 谢谢

**Comment by iczer** [comment]
参考 [Login.vue](https://github.com/iczer/vue-antd-admin/blob/master/src/pages/login/Login.vue)

**Comment by barrycom** [comment]
请问一下。这个项目是用的recat语言开发对吗？对比vue。这2个哪个适合这个后台项目的开发呢？或则说有antd+vue的吗？

**Comment by barrycom** [comment]
这个antd+vue版本的功能好像没有https://beta.preview.pro.ant.design/ 全。比如列表编辑弹窗没有。这个后面会更吗

**Comment by iczer** [comment]
一些功能细节目前还在开发中，会持续更新的哦，详见：[开发进度](https://github.com/iczer/vue-antd-admin/projects/1)。

有任何需求或疑问可以直接提 [issue](https://github.com/iczer/vue-antd-admin/issues/new) , 我会尽量优先开发 issues 中的需求或bug。

当然也可以 fork 本项目后自己添加相应功能，[ant-design-vue](https://github.com/vueComponent/ant-design-vue) 组件库比较丰富，应该可以满足大部分功能需求

**Comment by 18840857293** [comment]
请问一下，我这需要连接后台发送请求 请问我需要在哪里配置连接呢？

**Comment by iczer** [comment]
后台请求目前没有集中管理，可以在页面单独配置，可参考：[Login.vue](https://github.com/iczer/vue-antd-admin/blob/master/src/pages/login/Login.vue) 中的 onSubmit 方法
