### ISSUE TITLE
bug！！！主题模式默认修改为night 重启项目 刷新页面 无效

### ISSUE THREAD

**Issue by 2452815114** [iczer/vue-antd-admin#306]
` theme: {                              //主题
    color: '#1890ff',                   //主题色
    **mode: 'night',**                       //主题模式 可选 dark、 light 和 night
    success: '#52c41a',                 //成功色
    warning: '#faad14',                 //警告色
    error: '#f5222f',                   //错误色
  },`
两个文件都改了 mode: 'night‘ ；
重启项目刷新都无效
但页面的【整体风格设置】选中的却是深夜模式；而且当我再选择任意【主题色】 才变成深夜模式
求解 ！！！

**Comment by py-mu** [comment]
要不你试试点一下保存或者刷新一下浏览器缓存？
