### ISSUE TITLE
能否加个人页模块

### ISSUE THREAD

**Issue by suguoyao** [iczer/vue-antd-admin#31]
[react版pro](https://preview.pro.ant.design/account/settings/base)里有个人页模块（个人中心和个人设置）哈，这块有在计划之中吗？
![image](https://user-images.githubusercontent.com/16471605/46060967-7ca1c880-c197-11e8-9c69-ef1cd8ae801b.png)

**Comment by iczer** [comment]
有的，目前在开发权限管理模块，权限模块完成之后会补充个人页哈

**Comment by suguoyao** [comment]
> 有的，目前在开发权限管理模块，权限模块完成之后会补充个人页哈

好的谢谢哈哈 支持！

**Comment by iczer** [comment]
此项目暂时没有交流群哦，不过感兴趣的话可以加 [ant-design-vue](https://github.com/vueComponent/ant-design-vue/issues/17) 官方交流 QQ 群（217490093），里面昵称【稻草人】的就是我，欢迎哈

**Comment by nabaonan** [comment]
https://nabaonan.gitee.io/my-console/#/account/settings/base
