### ISSUE TITLE
多标签模式下，点击保存怎么关闭当前的标签呢？

### ISSUE THREAD

**Issue by onlyscv** [iczer/vue-antd-admin#312]
多标签模式下，点击保存怎么关闭当前的标签呢？

在就是，table表格，我们点击修改的时候，怎么设置弹出的标签是独立的。互相不影响。

**Comment by q8099090** [comment]
同求，解决了么

**Comment by onlyscv** [comment]
> 
关闭的解决了。弹出的好像没办法。

**Comment by q8099090** [comment]
我也遇到了多标签页面保存后关闭跳转的问题，大佬求下思路
