### ISSUE TITLE
请问如何在二级页面下新建一个三级页面

### ISSUE THREAD

**Issue by sountstars** [iczer/vue-antd-admin#318]
{
      path: "/",
      name: "1111",
      component: TabsView,
      redirect: "/list/query",
      children: [
        {
          path: "list",
          name: "222222",
          meta: {
            icon: "table",
          },
          component: PageView,
          children: [
            {
              path: "query",
              name: "222-1111",
              component: () => import("@/pages/list/questionnaire"),
              children: [
                {
                  path: "create",
                  name: "3333333",
                  meta: {
                    invisible: true,
                  },
                  //redirect: "create",
                  component: () => import("@/pages/list/questionnaire/create"),
                },
              ],
            },
          ],
        },
        
        
       create页面
       <template>
   <router-view>
    <a-card>
      新建11111111111
    </a-card>
  </router-view>
  </template>

**Comment by sountstars** [comment]
<template>
   <router-view>
    <a-card>
      新建11111111111
    </a-card>
  </router-view>
  </template>

**Comment by sountstars** [comment]
<img width="236" alt="image" src="https://user-images.githubusercontent.com/27804006/191407878-00701b6c-6c47-4c30-9789-4c4fb65d266a.png">

**Comment by sountstars** [comment]
what questions do you have?

**Comment by iczer** [comment]
在二级路由下添加 children 子路由即可。注意，你的所有父级页面都应该包含<router-view></router-view>，不然子页面是无法显示的；
