### ISSUE TITLE
Mac环境install失败报错

### ISSUE THREAD

**Issue by iwin4aids** [iczer/vue-antd-admin#32]
刚拉取的最新版本·全局安装yarn
执行yarn install报错如下：

jiangkundeMacBook-Pro:vue-antd-admin jiangkun$ yarn install
yarn install v1.10.1
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
[5/5] 📃  Building fresh packages...
[6/6] ⠐ level
[-/6] ⠐ waiting...
[-/6] ⠐ waiting...
[-/6] ⠐ waiting...
error /Users/jiangkun/frontend/vue-antd-admin/node_modules/chromedriver: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /Users/jiangkun/frontend/vue-antd-admin/node_modules/chromedriver
Output:

还望告知这个是什么错误引起的呢？

**Comment by iczer** [comment]
根据你的错误日志看，有可能是chromedriver下载失败了，可以切换国内镜像重新安装依赖试下。参考：[#2](https://github.com/iczer/vue-antd-admin/issues/2)

**Comment by iwin4aids** [comment]
> 根据你的错误日志看，有可能是chromedriver下载失败了，可以切换国内镜像重新安装依赖试下。参考：[#2](https://github.com/iczer/vue-antd-admin/issues/2)

还是不行，一直卡在那一步。不知道是不是我网络问题，我已经用的是国内镜像地址了。

**Comment by iczer** [comment]
> > 根据你的错误日志看，有可能是chromedriver下载失败了，可以切换国内镜像重新安装依赖试下。参考：[#2](https://github.com/iczer/vue-antd-admin/issues/2)
> 
> 还是不行，一直卡在那一步。不知道是不是我网络问题，我已经用的是国内镜像地址了。

有没有详细点的日志呢

**Comment by iwin4aids** [comment]
> > > 根据你的错误日志看，有可能是chromedriver下载失败了，可以切换国内镜像重新安装依赖试下。参考：[#2](https://github.com/iczer/vue-antd-admin/issues/2)
> > 
> > 
> > 还是不行，一直卡在那一步。不知道是不是我网络问题，我已经用的是国内镜像地址了。
> 
> 有没有详细点的日志呢

没有···控制台就卡在上面那一步，，，一直转圈：
yarn install v1.10.1
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
[5/5] 📃  Building fresh packages...
[6/6] ⡀ level
[-/6] ⡀ waiting...
[-/6] ⡀ waiting...
[-/6] ⡀ waiting...
[5/6] ⡀ chromedriver

**Comment by iwin4aids** [comment]
已经解决了哈～我把环境全部清理了一下，然后重新下载到所有包，ok了
