### ISSUE TITLE
这个path字段应该改成fullpath,要不然关闭页面后跳转的页面没有带上地址栏的参数

### ISSUE THREAD

**Issue by gc18773375617** [iczer/vue-antd-admin#320]
https://github.com/iczer/vue-antd-admin/blob/c0aec854afe11bfd607580dbc700884a0e7dcc3f/src/layouts/tabs/TabsView.vue#L133

**Comment by lpubcat** [comment]
改动后，会报错，请问这个问题后面如何修改。

**Comment by lpubcat** [comment]
我看此项目最新版本 没有这个问题，却不知道作者改动了哪里...

**Comment by iczer** [comment]
可能是这个提交：https://github.com/iczer/vue-antd-admin/commit/816d19f7da7b512f738ec15098018fb7e8f867ab
