### ISSUE TITLE
loadRoutes  函数  router.addRoutes(finalRoutes)  更换addRoute()报错

### ISSUE THREAD

**Issue by L5280999** [iczer/vue-antd-admin#324]
![image](https://user-images.githubusercontent.com/40187408/199668160-4b57b590-7c53-41c2-aea2-81abdd5f92d3.png)

**Comment by Jitianpeng** [comment]
vue-router升级后addRoute方法添加一个新的路由，是添加某一个路由，而组装完整的路由结构树，需要遍历之后逐个添加
