### ISSUE TITLE
a-input-group问题

### ISSUE THREAD

**Issue by zhanghq** [iczer/vue-antd-admin#33]
<a-input-group compact>
    <a-input style="width: 20%" defaultValue="0571" />
    <a-input style="width: 30%" defaultValue="26888888" />
  </a-input-group>

如果使用a-input-group，只能取到第二个输入框的值
如何取出完整的值？

**Comment by iczer** [comment]
[![Edit Vue Antd Template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wkyzqzkm37) 参考这个例子，目前ant-design-vue 官方 form 组件 使用 input-group时好像有些样式的问题，但不影响使用，可以自己修改样式
