### ISSUE TITLE
未来会有   vue3+Vite的版本么？

### ISSUE THREAD

**Issue by savelove** [iczer/vue-antd-admin#331]
vue3和vite使用的越来越广泛了 该项目后面有升级计划么？

**Comment by Andre235** [comment]
我不是该项目的开发者，观察repo的commit记录，发现不是很活跃了，所以应该不会有升级计划了。不过有能力的话可以自己升级。

**Comment by iczer** [comment]
vue3版本现已推出，更名为 [stepin-template](https://github.com/stepui/stepin-template) 欢迎体验
