### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by wangyi0127** [iczer/vue-antd-admin#335]
这种什么情况呢？找不到vue吗？还是说我版本有问题？
 ERROR  Failed to compile with 24 errors                                                                                                                                                                00:49:09
This dependency was not found:

* vue in ./node_modules/ant-design-vue/es/_util/openAnimation.js, ./node_modules/ant-design-vue/es/config-provider/index.js and 22 others

To install it, you can run: npm install --save vue

**Comment by iczer** [comment]
应该是安装 vue 失败了，可以单独尝试安装 vue
