### ISSUE TITLE
a-table 遍历数组 嵌入 a-popover 后整个table 行高变高

### ISSUE THREAD

**Issue by Messilimeng** [iczer/vue-antd-admin#337]
**Describe the bug**
![image](https://user-images.githubusercontent.com/12272166/228146097-7ec4bb74-de76-4cb2-8a17-95d0ac33da0c.png)
如果添加了这个tag 整个table 高度会变高

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [e.g. chrome]
   "ant-design-vue": "^1.7.8",
  "vue": "^2.6.11",
**Smartphone (please complete the following information):**

**Additional context**

**Comment by iczer** [comment]
不太明白你说的行变高具体是什么情况，可以入QQ群：695981885 发一下具体的异常截图。群里@我 或私信均可

**Comment by Messilimeng** [comment]
@iczer 解决了谢谢
