### ISSUE TITLE
yarn install安装出错

### ISSUE THREAD

**Issue by wolong438** [iczer/vue-antd-admin#35]
安装时，leveldown一直没动静，于是手动去下载leveldown时，也报错了。清除node_modules后重新安装也失败了。
虽然报错，但是项目能够启动。

E:\GitHub\vue-antd-admin>yarn install
yarn install v1.12.3
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
[-/5] ⠁ waiting...
[2/5] ⠁ leveldown
[-/5] ⠁ waiting...
[-/5] ⠁ waiting...
error E:\GitHub\vue-antd-admin\node_modules\leveldown: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments:
Directory: E:\GitHub\vue-antd-admin\node_modules\leveldown
Output:
prebuild-install WARN install No prebuilt binaries found (target=10.2.0 runtime=node arch=x64 platform=win32)

E:\GitHub\vue-antd-admin\node_modules\leveldown>if not defined npm_config_node_gyp (node "E:\node\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@10.2.0 | win32 | x64
gyp info spawn C:\Users\Administrator\.windows-build-tools\python27\python.exe
gyp info spawn args [ 'E:\\node\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\GitHub\\vue-antd-admin\\node_modules\\leveldown\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\node\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Administrator\\.node-gyp\\10.2.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Administrator\\.node-gyp\\10.2.0',
gyp info spawn args   '-Dnode_gyp_dir=E:\\node\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Administrator\\.node-gyp\\10.2.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=E:\\GitHub\\vue-antd-admin\\node_modules\\leveldown',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'E:\\GitHub\\vue-antd-admin\\node_modules\\leveldown\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
�ڴ˽��������һ������һ����Ŀ����Ҫ���ò������ɣ������ӡ�/m�����ء�
  builder.cc
  db_impl.cc
  db_iter.cc
  filename.cc
  dbformat.cc
  log_reader.cc
  log_writer.cc
  memtable.cc
  repair.cc
  table_cache.cc
  version_edit.cc
e:\github\vue-antd-admin\node_modules\leveldown\deps\leveldb\leveldb-1.20\db\skiplist.h(360): warning C4312: ��reinterpret_cast��: �ӡ�int��ת��������ġ�void *�� (����Դ�ļ� leveldb-1.2
0\db\memtable.cc) [E:\GitHub\vue-antd-admin\node_modules\leveldown\deps\leveldb\leveldb.vcxproj]
  e:\github\vue-antd-admin\node_modules\leveldown\deps\leveldb\leveldb-1.20\db\skiplist.h(337): note: ���� �� ģ�� ��Ա���� "void leveldb::SkipList<const char *,leveldb::MemTable::KeyComparator>
::Insert(const Key &)" ʱ
          with
          [
              Key=const char *
          ] (����Դ�ļ� leveldb-1.20\db\memtable.cc)
  e:\github\vue-antd-admin\node_modules\leveldown\deps\leveldb\leveldb-1.20\db\memtable.cc(105): note: �μ������ڱ���ĺ��� ģ�� ʵ������void leveldb::SkipList<const char *,leveldb::MemTabl
e::KeyComparator>::Insert(const Key &)��������
          with
          [
              Key=const char *
          ]
  e:\github\vue-antd-admin\node_modules\leveldown\deps\leveldb\leveldb-1.20\db\memtable.h(79): note: �μ������ڱ���� �� ģ�� ʵ���� "leveldb::SkipList<const char *,leveldb::MemTable::KeyCom
parator>" ������ (����Դ�ļ� leveldb-1.20\db\memtable.cc)
  version_set.cc
  write_batch.cc
  memenv.cc
  port_posix_sse.cc
  block.cc
  block_builder.cc
  filter_block.cc
  format.cc
  iterator.cc
  merger.cc
  table.cc
  table_builder.cc
  two_level_iterator.cc
  arena.cc
  bloom.cc
  cache.cc
  coding.cc
  comparator.cc
  crc32c.cc
  env.cc
  filter_policy.cc
  hash.cc
  logging.cc
  options.cc
  status.cc
  port_uv.cc
  env_win.cc
  win_logger.cc
  win_delay_load_hook.cc
  leveldb.vcxproj -> E:\GitHub\vue-antd-admin\node_modules\leveldown\build\Release\\leveldb.lib
  snappy-sinksource.cc
  snappy-stubs-internal.cc
  snappy.cc
  win_delay_load_hook.cc
e:\github\vue-antd-admin\node_modules\leveldown\deps\snappy\snappy-1.1.4\snappy-stubs-internal.h : warning C4819: ���ļ����������ڵ�ǰ����ҳ(936)�б�ʾ���ַ����뽫���ļ�����Ϊ U
nicode ��ʽ�Է�ֹ���ݶ�ʧ (����Դ�ļ� snappy-1.1.4\snappy.cc) [E:\GitHub\vue-antd-admin\node_modules\leveldown\deps\snappy\snappy.vcxproj]
e:\github\vue-antd-admin\node_modules\leveldown\deps\snappy\snappy-1.1.4\snappy-stubs-internal.h : warning C4819: ���ļ����������ڵ�ǰ����ҳ(936)�б�ʾ���ַ����뽫���ļ�����Ϊ U
nicode ��ʽ�Է�ֹ���ݶ�ʧ (����Դ�ļ� snappy-1.1.4\snappy-stubs-internal.cc) [E:\GitHub\vue-antd-admin\node_modules\leveldown\deps\snappy\snappy.vcxproj]
  snappy.vcxproj -> E:\GitHub\vue-antd-admin\node_modules\leveldown\build\Release\\snappy.lib
  batch.cc
  batch_async.cc
  database.cc
  database_async.cc
c:\users\administrator\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: �޷�������ļ�: ��core.h��: No such file or directory (����Դ�ļ� ..\src\batch.cc) [E:\GitHub\vue-antd-admi
n\node_modules\leveldown\build\leveldown.vcxproj]
c:\users\administrator\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: �޷�������ļ�: ��core.h��: No such file or directory (����Դ�ļ� ..\src\database.cc) [E:\GitHub\vue-antd-a
dmin\node_modules\leveldown\build\leveldown.vcxproj]
  iterator.cc
  iterator_async.cc
c:\users\administrator\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: �޷�������ļ�: ��core.h��: No such file or directory (����Դ�ļ� ..\src\database_async.cc) [E:\GitHub\vue-
antd-admin\node_modules\leveldown\build\leveldown.vcxproj]
  leveldown.cc
c:\users\administrator\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: �޷�������ļ�: ��core.h��: No such file or directory (����Դ�ļ� ..\src\iterator_async.cc) [E:\GitHub\vue-
antd-admin\node_modules\leveldown\build\leveldown.vcxproj]
  leveldown_async.cc
c:\users\administrator\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: �޷�������ļ�: ��core.h��: No such file or directory (����Դ�ļ� ..\src\leveldown.cc) [E:\GitHub\vue-antd-
admin\node_modules\leveldown\build\leveldown.vcxproj]
c:\users\administrator\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: �޷�������ļ�: ��core.h��: No such file or directory (����Դ�ļ� ..\src\iterator.cc) [E:\GitHub\vue-antd-a
dmin\node_modules\leveldown\build\leveldown.vcxproj]
  win_delay_load_hook.cc
c:\users\administrator\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: �޷�������ļ�: ��core.h��: No such file or directory (����Դ�ļ� ..\src\batch_async.cc) [E:\GitHub\vue-ant
d-admin\node_modules\leveldown\build\leveldown.vcxproj]
c:\users\administrator\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: �޷�������ļ�: ��core.h��: No such file or directory (����Դ�ļ� ..\src\leveldown_async.cc) [E:\GitHub\vue
-antd-admin\node_modules\leveldown\build\leveldown.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\node\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "E:\\node\\node.exe" "E:\\node\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\GitHub\vue-antd-admin\node_modules\leveldown

====================================================
E:\GitHub\vue-antd-admin>npm install levelup leveldown
npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated domelementtype@1.3.0: update to domelementtype@1.3.1
npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN deprecated bfj-node4@5.3.1: Switch to the `bfj` package for fixes and new features!
npm WARN rm not removing E:\GitHub\vue-antd-admin\node_modules\.bin\prebuild-install.cmd as it wasn't installed by E:\GitHub\vue-antd-admin\node_modules\prebuild-install
npm WARN rm not removing E:\GitHub\vue-antd-admin\node_modules\.bin\prebuild-install as it wasn't installed by E:\GitHub\vue-antd-admin\node_modules\prebuild-install
npm WARN rm not removing E:\GitHub\vue-antd-admin\node_modules\.bin\uuid.cmd as it wasn't installed by E:\GitHub\vue-antd-admin\node_modules\uuid
npm WARN rm not removing E:\GitHub\vue-antd-admin\node_modules\.bin\uuid as it wasn't installed by E:\GitHub\vue-antd-admin\node_modules\uuid
npm WARN rm not removing E:\GitHub\vue-antd-admin\node_modules\.bin\uglifyjs.cmd as it wasn't installed by E:\GitHub\vue-antd-admin\node_modules\uglify-js
npm WARN rm not removing E:\GitHub\vue-antd-admin\node_modules\.bin\uglifyjs as it wasn't installed by E:\GitHub\vue-antd-admin\node_modules\uglify-js
npm WARN rm not removing E:\GitHub\vue-antd-admin\node_modules\.bin\jsesc.cmd as it wasn't installed by E:\GitHub\vue-antd-admin\node_modules\jsesc
npm WARN rm not removing E:\GitHub\vue-antd-admin\node_modules\.bin\jsesc as it wasn't installed by E:\GitHub\vue-antd-admin\node_modules\jsesc
npm WARN rm not removing E:\GitHub\vue-antd-admin\node_modules\.bin\jest.cmd as it wasn't installed by E:\GitHub\vue-antd-admin\node_modules\jest-cli
npm WARN rm not removing E:\GitHub\vue-antd-admin\node_modules\.bin\jest as it wasn't installed by E:\GitHub\vue-antd-admin\node_modules\jest-cli
npm WARN rm not removing E:\GitHub\vue-antd-admin\node_modules\.bin\browserslist.cmd as it wasn't installed by E:\GitHub\vue-antd-admin\node_modules\browserslist
npm WARN rm not removing E:\GitHub\vue-antd-admin\node_modules\.bin\browserslist as it wasn't installed by E:\GitHub\vue-antd-admin\node_modules\browserslist
npm WARN rm not removing E:\GitHub\vue-antd-admin\node_modules\.bin\babylon.cmd as it wasn't installed by E:\GitHub\vue-antd-admin\node_modules\babylon
npm WARN rm not removing E:\GitHub\vue-antd-admin\node_modules\.bin\babylon as it wasn't installed by E:\GitHub\vue-antd-admin\node_modules\babylon

> leveldown@3.0.0 install E:\GitHub\vue-antd-admin\node_modules\leveldown
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=10.2.0 runtime=node arch=x64 platform=win32)

E:\GitHub\vue-antd-admin\node_modules\leveldown>if not defined npm_config_node_gyp (node "C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 98, in Load
    generator.CalculateVariables(default_variables, params)
  File "C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1916, in CalculateVariables
    generator_flags.get('msvs_version', 'auto'))
  File "C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 434, in SelectVisualStudioVersion
    versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
KeyError: '2017'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "E:\\node\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\GitHub\vue-antd-admin\node_modules\leveldown
gyp ERR! node -v v10.2.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@3.0.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leveldown@3.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-12-13T10_20_35_626Z-debug.log

**Comment by wolong438** [comment]
yarn install安装项目，貌似默认下载的是leveldown@3.0.0，但是yarn.lock中配置的leveldown@3.0.0的地址找不到响应的文件，我把leveldown响应的配置改成3.0.1版本就可以成功安装了。
如果安装时chromedriver没有动静（安装不了），安装前`yarn config set "chromedriver_cdnurl" "https://npm.taobao.org/mirrors/chromedriver"`就可以了

**Comment by quavario** [comment]
升级pouchdb为最新版本，或者直接删掉pouchdb依赖，同时在`main.js`中手动添加一个用户信息
```
new Vue({
  el: '#app',
  router,
  store,
  components: { App },
  template: '<App/>',
  mounted () {
    const user = {
      address: '湘潭市',
      avatar: 'https://gw.alipayobjects.com/zos/rmsportal/WhxKECPNujWoWEFNdnJE.png',
      name: 'DAVID',
      position: '前端工程师 | 蚂蚁金服-计算服务事业群-REACT平台',
      timefix: '上午好',
      welcome: '准备吃什么呢'
    }
    this.$store.commit('account/setuser', user)
  }
})

```
