### ISSUE TITLE
主题色更换不了

### ISSUE THREAD

**Issue by wolong438** [iczer/vue-antd-admin#37]
系统界面选中主题色之后，弹框提示“您选择了主题色 rgb(250, 173, 20)”，跟demo页面的“正在编译***”不一样，而且主题色也没有变化。

**Comment by wolong438** [comment]
仓主可以参考这个项目：https://github.com/ant-design/ant-design-pro

**Comment by iczer** [comment]
主题色切换功能尚未实现，感谢建议。
鉴于关于ant design pro项目 已有大大已经做得比本项目更完善，建议fork 或直接参考https://github.com/ant-design/ant-design-pro
