### ISSUE TITLE
可以用于管理系统么

### ISSUE THREAD

**Issue by xx6822** [iczer/vue-antd-admin#38]
您好，这个项目非常棒，我在搭建一个管理系统，前台打算采用您的框架，请问可以吗？我会在Readme.md里标注的~

**Comment by iczer** [comment]
可以的，本项目遵循 MIT 开源协议 。
鉴于目前本项目只做了常见页面的简单示例，如需更多完善的功能建议参考或 fork https://github.com/ant-design/ant-design-pro

**Comment by xx6822** [comment]
好的，谢谢！
