### ISSUE TITLE
希望可以继续更新维护

### ISSUE THREAD

**Issue by Y09a** [iczer/vue-antd-admin#39]
这么棒的项目真的不希望她被停止更新维护， 希望她可以同Ant.D和Vue一起茁壮成长。

**Comment by nabaonan** [comment]
作者是不是太忙了，感觉这个项目好久没有更新过了，不过社区还有别的可以用

**Comment by iczer** [comment]
感谢关注，因个人事务，这段时间确实有点忙，所以断更了很久，对此深表抱歉。
春节后会重拾该项目；
另社区也有很多的优秀的产品，欢迎关注：https://github.com/vueComponent/ant-design-vue-awesome
