### ISSUE TITLE
使用PageView切换的页面"desc"会找不到

### ISSUE THREAD

**Issue by myronlau** [iczer/vue-antd-admin#4]
重现：登录之后默认工作台，然后点击表单页的基础表单，再点回来工作台就会报"desc"找不到，不清楚desc是什么时候取值的。

**Comment by iczer** [comment]
已解决  [74f9727](https://github.com/iczer/vue-antd-admin/commit/74f972734097c94a0e16ca30c7fa944a52bc412c)
