### ISSUE TITLE
Tab页切换优化

### ISSUE THREAD

**Issue by xx6822** [iczer/vue-antd-admin#41]
当前Tab页面切换虽然有淡入淡出的动画，但不同Tab页面内容不一样，所以高度也不一样，在切换的时候页面会抖（闪，比如页面高度由1000px过渡到500px的时候），请问有没什么办法优化呢(✿◕‿◕✿)

**Comment by iczer** [comment]
额，我这里暂时没发现闪动的情况，可以提供下你的环境吗：浏览器型号、系统类型

**Comment by xx6822** [comment]
比如快速切换

https://iczer.gitee.io/vue-antd-pro/#/result/success 和 https://iczer.gitee.io/vue-antd-pro/#/result/error

就是在想又没办法让页面切换时有个全屏的加载动画，页面内容全部渲染完毕后，再移除这个动画

**Comment by qmt216** [comment]
我和楼主遇到同样的问题，win10， chrome74. 不过在同样的环境我看您的预览项目确实没有这个问题，不知道问题出在哪儿

**Comment by qmt216** [comment]
![01](https://user-images.githubusercontent.com/8164644/59818566-05304c80-9357-11e9-8d5b-16202085cb10.gif)

**Comment by qmt216** [comment]
我把最新的完整代码下载了运行，同样有这样的问题存在，应该是上传的代码和预览地址的代码不一样，望尽快更新下，谢谢！

**Comment by daifuying** [comment]
> 我把最新的完整代码下载了运行，同样有这样的问题存在，应该是上传的代码和预览地址的代码不一样，望尽快更新下，谢谢！

跟你截图遇到同样的问题，mac本，解决了么

**Comment by iczer** [comment]
已修复，更新至最新代码
