### ISSUE TITLE
关于给路由增加keep-alive判定

### ISSUE THREAD

**Issue by EricHan0723** [iczer/vue-antd-admin#42]
现在有一问题就是，我用了框架后，需要除了有左侧菜单的一级页面之外，每个一级页面还有下面的二级子页面，所以我想要在进入二级子页面再返回它的父页面的时候，缓存当前父页面
比如 有 【1,2,3】3个一级页面，当我从1跳转到1-1的子页面，再返回1时，1的页面是缓存着的，如果是从1-1跳转到2，则2是重新加载页面
我在App.vue里增加了
```
<keep-alive>
    <router-view v-if="$route.meta.keepAlive"></router-view>
</keep-alive>
<router-view v-if="!$route.meta.keepAlive"></router-view>
```
并在router的lazy.js为需要缓存的页面增加了`meta: { keepAlive: true }`

但是现在出现的问题是，经常会出现点击菜单跳转的页面会不是当前路由的页面，而是缓存的页面，我想问一下，是不是我的实现有问题，还是框架有什么地方可以直接设置呢？

**Comment by iczer** [comment]
App.vue里放了应用的根路由，不适合来控制页面路由的状态。
如果你想控制具体页面的状态，应该在其它路由组件里控制：MenuView RouteView PageView
你仔细看看 [lazy.js](https://github.com/iczer/vue-antd-admin/blob/master/src/router/lazy.js) 的配置，我想你应该需要在[ MenuView.vue](https://github.com/iczer/vue-antd-admin/blob/master/src/layouts/MenuView.vue) [RouteView.vue](https://github.com/iczer/vue-antd-admin/blob/master/src/layouts/RouteView.vue) [PageView.vue](https://github.com/iczer/vue-antd-admin/blob/master/src/layouts/PageView.vue) 里控制

![image](https://user-images.githubusercontent.com/13096697/51735132-7da12300-20c1-11e9-8391-0a6898fdc6dc.png)
