### ISSUE TITLE
跨域问题

### ISSUE THREAD

**Issue by 18840857293** [iczer/vue-antd-admin#43]
想请问下如何解决跨域问题呢，在不用后台修改代码的前提下？

**Comment by AberSheeran** [comment]
后台不修改代码？你怎么跨域？只能拿Nginx反代一波，加头了

**Comment by SailShaw** [comment]
写一个CorsConfig类就可以了,ajax里直接localhost:8080+请求地址,几十行代码的事儿,又不是对后端代码大刀阔斧的搞.

**Comment by fuuqiu** [comment]
跨域问题最好是在nginx代理层处理
