### ISSUE TITLE
怎么根据请求返回值，更换menu菜单

### ISSUE THREAD

**Issue by cuiwang137** [iczer/vue-antd-admin#48]
不同的角色登陆需要不同的左侧menu菜单 因此需要方法更换菜单

**Comment by specYyt** [comment]
我也遇到了这个问题，解决了吗，动态路由不给力啊，全变成了RouterView，然后就是大白板

**Comment by iczer** [comment]
如需要动态更换菜单，不建议用项目自带菜单组件（项目菜单组件是根据路由傻瓜式生成的，不适用此场景），可以尝试用 [ant-design-vue menu](https://www.antdv.com/components/menu-cn/#Menu-) 组件试试自己实现哈
