### ISSUE TITLE
为啥我 yarn install报错，yarn版本是1.15.报错

### ISSUE THREAD

**Issue by alilyrace** [iczer/vue-antd-admin#49]
error H:\project\vue-antd-admin\vue-antd-admin\node_modules\leveldown: Command f
ailed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments:
Directory: H:\project\vue-antd-admin\vue-antd-admin\node_modules\leveldown
Output:
prebuild-install WARN install No prebuilt binaries found (target=10.15.0 runtime
=node arch=x64 platform=win32)

**Comment by Hew007** [comment]
同上，刚pull到本地，install就报错了

**Comment by hehaibao** [comment]
我升级了下yarn到最新版本就好了~

**Comment by zchu-zhaowei** [comment]
我也报同样的错
yarn install v1.16.0-20190420.1726
[4/5] ⠄ chromedriver
error E:\zchu\AntDesignVue\vue-antd-admin\node_modules\leveldown: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments:
Directory: E:\zchu\AntDesignVue\vue-antd-admin\node_modules\leveldown
Output:
The system cannot find the path specified.
The system cannot find the path specified.

**Comment by BoyceShi** [comment]
yarn version: 1.22.4
node version:12.18.0
```
 c:\my workspace\vue-antd-admin\node_modules\level\node_modules\leveldown\src\database.cc(463): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\My Workspace\vue-antd-admin\node_modules\level\node_modules\leveldown
```
The same scenario.

**Comment by BoyceShi** [comment]
> yarn version: 1.22.4
> node version:12.18.0
> 
> ```
>  c:\my workspace\vue-antd-admin\node_modules\level\node_modules\leveldown\src\database.cc(463): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
> gyp ERR! build error
> gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
> gyp ERR! System Windows_NT 10.0.19041
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\My Workspace\vue-antd-admin\node_modules\level\node_modules\leveldown
> ```
> 
> The same scenario.

Use npm install successful. 
 npm install --global windows-build-tools first.
But yarn has the same issue yet.

**Comment by iczer** [comment]
更新至最新代码试下哈。
try update to the latest code

**Comment by BoyceShi** [comment]
@iczer 
Problem solved, thank you for your contribution.
