### ISSUE TITLE
样式问题？喵喵喵

### ISSUE THREAD

**Issue by yihuishou** [iczer/vue-antd-admin#5]
![qq 20180813102119](https://user-images.githubusercontent.com/26241263/44010048-a6f4d60e-9ee2-11e8-91da-a1d7785936ac.png)

菜单边框好像缺阴影的说？

**Comment by iczer** [comment]
![image](https://user-images.githubusercontent.com/13096697/44011272-40164884-9eea-11e8-9e53-51f5e9b70d5b.png)
是指hover 背景吗？

**Comment by iczer** [comment]
目前参考 [ant design pro](https://preview.pro.ant.design/#/dashboard/analysis) 设计开发，Header 菜单边框不设置阴影。如有需要，可以自己添加哈

**Comment by yihuishou** [comment]
ant design pro 有阴影的说 QAQ

**Comment by iczer** [comment]
你指的莫非是 hover 背景 
![image](https://user-images.githubusercontent.com/13096697/44024322-8726910e-9f1f-11e8-9976-ae5f00b9ed38.png)

**Comment by iczer** [comment]
可否详细描述下

**Comment by yihuishou** [comment]
![qq 20180813191842](https://user-images.githubusercontent.com/26241263/44028818-b6f172c4-9f2d-11e8-9dff-900241546593.png)
这里的阴影

**Comment by iczer** [comment]
感谢！已修复：[13fdf91](https://github.com/iczer/vue-antd-admin/commit/13fdf915d7c379c289abd5b4f134aa148aaf1925)

**Comment by yihuishou** [comment]
![qq 20180814085501](https://user-images.githubusercontent.com/26241263/44065864-dbba388a-9f9f-11e8-9bba-a7f74c88843f.png)

文字沉下去啦~

**Comment by yihuishou** [comment]
![qq 20180814090051](https://user-images.githubusercontent.com/26241263/44065998-a733b9dc-9fa0-11e8-9a9a-35f1317dd504.png)
通知也沉下去啦 （趴）

**Comment by iczer** [comment]
好眼力(￣▽￣)／，已修复：[ac4177f](https://github.com/iczer/vue-antd-admin/commit/ac4177fa52ac57e6c08947247017bafba6425eb3)
