### ISSUE TITLE
菜单组件为什么要用渲染函数而不是.vue文件

### ISSUE THREAD

**Issue by zhouyunjie** [iczer/vue-antd-admin#52]
如题  主要是看.vue组件看习惯了  突然看到这个有点蒙圈  这样写有什么特殊意义吗？

**Comment by iczer** [comment]
因为菜单是根据路由配置文件自动生成的，涉及到渲染函数的递归，用 vue 组件实现起来比较麻烦，所以选用了 js 代码实现。
