### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by RichardWSD** [iczer/vue-antd-admin#56]
ERROR  Failed to compile with 1 errors                                                                         19:32:47

This dependency was not found:

* ant-design-vue/es/icon/icon in ./src/components/menu/menu.js

To install it, you can run: npm install --save ant-design-vue/es/icon/icon

**Comment by zhangxin-github** [comment]
同问。

**Comment by zhangxin-github** [comment]
找到解决方法：
进入/vue-antd-admin/src/components/menu/menu.js 文件，修改原来：

import Icon from 'ant-design-vue/es/icon/icon'
为:
import Icon from 'ant-design-vue/es/icon'

即可。
