### ISSUE TITLE
我想在子页面里边通过一个按钮点击关闭子页面然后移除当前多页签但是好像找不到父组件MenuView里边的方法

### ISSUE THREAD

**Issue by qwe605052330** [iczer/vue-antd-admin#58]
我想在子页面里边通过一个按钮点击关闭子页面然后移除当前多页签但是好像找不到父组件MenuView里边的方法

**Comment by iczer** [comment]
可以通过 vuex 实现哈，把 MenuView 里的 pageList 存放在 vuex 中，然后子页面更新 vuex 就可以了
