### ISSUE TITLE
新增成员只能添加一个，算上项目里面默认的三个

### ISSUE THREAD

**Issue by hello-V** [iczer/vue-antd-admin#69]
在表单页里面的高级表单里面最下面的用户管理。点击新增成员可以填写一行内容（有项目里面默认有的三个成员信息），再点击添加新增成员就报错了，而且添加不了新成员。

**Comment by iczer** [comment]
已修复，[a023e74](https://github.com/iczer/vue-antd-admin/commit/a023e7437ceb5c6a05105c950c74020e174870cd)
