### ISSUE TITLE
建议加登录拦截器

### ISSUE THREAD

**Issue by nabaonan** [iczer/vue-antd-admin#7]
从登录页直接输入dashboard很容易绕过去

**Comment by iczer** [comment]
good idea! 后面会加入拦截器

**Comment by iczer** [comment]
Good idea! 后面会加入拦截器

**Comment by yihuishou** [comment]
建议加 动态路由菜单？ 喵喵喵~

**Comment by iczer** [comment]
目前已实现根据路由配置自动生成菜单，不知道你说的动态路由菜单是不是指这个 @yihuishou

**Comment by yihuishou** [comment]
就是用户权限生成路由表吧

**Comment by iczer** [comment]
明白了

**Comment by nabaonan** [comment]
建议实现根据权限id筛选路由

**Comment by 107295472** [comment]
@iczer  路由参考一下这个https://github.com/PanJiaChen/vue-element-admin
有QQ群吗

**Comment by iczer** [comment]
@107295472 感谢建议，此项目暂时还没有qq讨论群哦。如感兴趣可加 ant-design-vue 组件讨论群 217490093 ，里面有很多大牛

**Comment by iczer** [comment]
See [4e6a060](https://github.com/iczer/vue-antd-admin/commit/4e6a060dfe743e28d71b099b36e475960f86432f)
