### ISSUE TITLE
请问一下，重复点击菜单栏同一目录的问题

### ISSUE THREAD

**Issue by FrankFubin** [iczer/vue-antd-admin#75]
您好，请问一下，如图所示，左侧菜单栏点击同一目录两次时，第二次点击后没有跳转操作，但是页面整体向上移动了一下，这个问题怎么解？
![TIM图片20200614152130](https://user-images.githubusercontent.com/26758808/84587611-41579980-ae53-11ea-8014-9eae5a85ca0f.png)

**Comment by iczer** [comment]
这边没复现出您的问题哈，请尝试更新代码看看问题是否还存在哈
