### ISSUE TITLE
屏幕长度不够时，tab反复变化

### ISSUE THREAD

**Issue by Cyberist-Edgar** [iczer/vue-antd-admin#80]
非PC端或者PC端的窗口长度不够，查看的时候可能出现下图情况

<img src='https://user-images.githubusercontent.com/47896650/85505039-f5a9aa80-b61f-11ea-9a2a-717f714852fa.gif' width="200px">

**Comment by iczer** [comment]
移动端兼容工作还没正式开始，不过在计划中哈 ，敬请关注 👀

**Comment by iczer** [comment]
已修复，👁️[9caba7c](https://github.com/iczer/vue-antd-admin/commit/9caba7cc6609dcc071985fa99fd41f452e78fe7c)
