### ISSUE TITLE
多页签模式，关闭当前页签后，页面没切换

### ISSUE THREAD

**Issue by junyi5d** [iczer/vue-antd-admin#82]
多页签的页面，关闭当前页签，应该将页面也切换到之前打开的上一页才对吧，目前只关闭了标签，页面不变

**Comment by iczer** [comment]
已修复，查看 [9dcf655](https://github.com/iczer/vue-antd-admin/commit/9dcf6557cf8d437f12b927025a106918dfb991ac)；

首先，感谢报告此bug。 😃 

另外，关闭当前页签不会打开上一次的页面，而是打开被关闭页签的相邻页签。参考浏览器页签关闭逻辑
