### ISSUE TITLE
yarn install 报错了

### ISSUE THREAD

**Issue by kang558** [iczer/vue-antd-admin#83]
#### 如图：

![image](https://user-images.githubusercontent.com/22288837/85940872-c5c91280-b951-11ea-90d1-9c90f4b7d1e9.png)

**Comment by iczer** [comment]
有没有详细的报错信息呢

**Comment by iczer** [comment]
依赖安装错误，可尝试更换国内镜像，如果还是不行，提供下详细的报错信息
```
npm config set registry https://registry.npm.taobao.org --global
yarn config set registry https://registry.npm.taobao.org --global
```

**Comment by kang558** [comment]
换了，报错和上面的一样
下面是运行报错
![image](https://user-images.githubusercontent.com/22288837/85941204-0cb80780-b954-11ea-8757-30a0480b89c6.png)

**Comment by iczer** [comment]
这是全部的报错信息了吗

**Comment by kang558** [comment]
> 这是全部的报错信息了吗
放错图了，更新，看一下
是全部报错信息了

**Comment by iczer** [comment]
从你截图看，是安装 ejs 这个依赖的时候报错了，但是这里没详细的错误信息，不好推断是什么原因，可能跟你的电脑环境相关。
我查下 相关资料，也建议你 从 ejs 着手查一下。
另外，建议不要用 git 的 bash 工具执行这些命令，最好用系统自带的 CMD 工具 或者 编辑器带的命令行工具

**Comment by iczer** [comment]
参考下这个，强制安装 下 ejs 试下：
[ejs3-1-3-postinstall](https://stackoverflow.com/questions/62098782/ejs3-1-3-postinstall-node-harmony-postinstall-js-exit-status-1)

**Comment by kang558** [comment]
试了还是不行，用npm就可以 😂

**Comment by iczer** [comment]
不知道你那是具体什么情况，不过用npm也是一样的 :smile:
