### ISSUE TITLE
history模式

### ISSUE THREAD

**Issue by dy2001** [iczer/vue-antd-admin#85]
将路由模式更改为history模式切换路由时报错

![](https://s1.ax1x.com/2020/07/07/UFHKTU.jpg)

能否考虑支持下history模式

截图
![](https://s1.ax1x.com/2020/07/07/UFT2vt.png)
![](https://s1.ax1x.com/2020/07/07/UF7mIe.png)

**Comment by iczer** [comment]
想使用 history 模式，把vue 配置文件 vue.config.js 中 publicPath 由 ‘./’ 改为 ‘/’ 即可，如：
```diff
module.exports = {
...
- publicPath: './',
+ publicPath: '/',
  outputDir: 'dist',
  assetsDir: 'static',
  productionSourceMap: false
}

```
