### ISSUE TITLE
导航动态获取后未更新

### ISSUE THREAD

**Issue by zxzhuty** [iczer/vue-antd-admin#90]
你好，在使用这个框架中，在AdminLayout页面，menuData我使用了vuex中的数据，可是当修改vuex中的数据后（通过axios获取的网络数据），AdminLayout中side-menu并未响应式的更新。请问这里是我有什么做得不对的吗

**Comment by iczer** [comment]
能提供下仓库地址，或者复现demo 吗。我试过动态更新 menuData 是没问题的
