### ISSUE TITLE
请问，系统如何集成单点登录？

### ISSUE THREAD

**Issue by bzcyer** [iczer/vue-antd-admin#92]
目前系统鉴权是采用的单点登录的方式实现，基于PHP开发的系统是集成了phpCAS组件实现。

这边要实现SSO的话，该怎么操作呢？

**Comment by iczer** [comment]
单点登录应该是后端的工作，这是个前端项目哦

**Comment by bzcyer** [comment]
后端用php和flask都是先了对cas的调用，但不熟悉vue，不知道前端怎么配合用，后端cas地址：http://xxxxx/auth_cas_login.php
