### ISSUE TITLE
模块导入错误

### ISSUE THREAD

**Issue by whoismonay** [iczer/vue-antd-admin#93]
src/utils/colors.js文件中
const generate =  require('@ant-design/colors/lib/generate').default代码导入模块出错！
应改成 const generate =  require('@ant-design/colors').generate

**Comment by iczer** [comment]
感谢提出的问题。
这个貌似最近 npm 和 cnpm 包安装 @ant-design/colors@4.01出现的问题。
尝试了下使用 npm 和 cnpm 安装@ant-design/colors@4.01依赖时，和 用yarn 安装@ant-design/colors@4.01依赖 下载的包内容不一样。前者 缺失了@ant-design/colors/lib/generate.js 文件。
但刚开始使用这个版本时两种安装方式是没有区别的，我的项目中之前也一直使的是@ant-design/colors/lib/generate，现在初步验证了下@ant-design/colors.generate 应该是没问题的，应该很快更新这个bug.
