### ISSUE TITLE
当默认主题模式改为light，会显示异常

### ISSUE THREAD

**Issue by Jarod-Xie** [iczer/vue-antd-admin#94]
**Describe the bug**
根据 [主题色模式切换](https://iczer.github.io/vue-antd-admin/develop/theme.html#%E4%B8%BB%E9%A2%98%E6%A8%A1%E5%BC%8F) 在`src/config/config.js` 中把默认主题色改为 `light` ，登录界面仍是黑色。登录后显示也有异常

**Screenshots**
![image](https://user-images.githubusercontent.com/27668637/88645034-3e102880-d0f6-11ea-9dc4-be59f55b6096.png)
![image](https://user-images.githubusercontent.com/27668637/88645172-67c94f80-d0f6-11ea-9c7d-609f33874489.png)

**Desktop (please complete the following information):**
 - chrome

**Additional context**

**Comment by iczer** [comment]
配置文件修改配置文件后需要重启服务

**Comment by Jarod-Xie** [comment]
的确可以了，谢谢。不过我一直理解的是src目录下的文件修改后应该是不需要重启服务的，vue.config.js 这种开发环境的配置文件才需要重启，是我理解有问题吗？

**Comment by iczer** [comment]
因为涉及到主题初始化的问题，当你更改主题颜色或者主题模式时 vue.config.js 里面有关于主题的配置会相应更改，所以需要重启服务

**Comment by Jarod-Xie** [comment]
明白了，谢谢
